Repository mattermost/mattermost-redux, pull requests merged in 2018-10, with the labels that each got.

#653 Fixing flow errors
  src/actions/admin.js
  src/actions/general.js
  src/selectors/entities/general.js
  src/types/actions.js
  src/types/requests.js
Labels: 3: Ready to Merge

#652 MM-12067: Add SetDefaultProfileImage client api and action
  src/actions/users.js
  src/client/client4.js
  test/actions/users.test.js
Labels: 3: Ready to Merge

#659 MM-11044 Add flow annotations to preferences actions
  src/actions/preferences.js
  src/types/actions.js
  src/types/preferences.js
  src/types/store.js
Labels: 2: Dev Review

#663 [MM-12490] Fix test on node version 10
  test/actions/channels.test.js
  test/selectors/channels.test.js
Labels: 2: Dev Review

#666 MM-11477 Changes required to intercept leaked network errors on mobile
  src/client/client4.js
  src/store/configureStore.dev.js
  src/store/configureStore.prod.js
  src/store/helpers.js
  src/store/middleware.js
Labels: 3: Ready to Merge

#670 MM-12521 Fix custom emoji not returning results
  src/client/client4.js
Labels: 3: Ready to Merge, CherryPickApproved

#651 MM-11880 Have Team Settings modal use the patch endpoint instead of the update endpoint
  .gitignore
  src/action_types/teams.js
  src/actions/teams.js
  src/actions/websocket.js
  src/client/client4.js
  src/reducers/entities/teams.js
  src/reducers/requests/teams.js
  src/store/initial_state.js
  src/types/requests.js
  test/actions/teams.test.js
  test/actions/websocket.test.js
Labels: 3: Ready to Merge, Hacktoberfest

#671 Refactored to rename "service terms" to "terms of service"
  src/action_types/users.js
  src/actions/admin.js
  src/actions/users.js
  src/client/client4.js
  src/reducers/requests/users.js
  src/selectors/entities/users.js
  test/actions/users.test.js
  test/selectors/users.test.js
Labels: 3: Ready to Merge, CherryPickApproved

#674 Update package.json
  package.json
Labels: 2: Dev Review

#676 Add getRelativeTeamUrl selector
  src/selectors/entities/teams.js
  test/selectors/teams.test.js
Labels: 3: Ready to Merge

#673 MM-12346: Checks permissions to edit post regardless of license.
  src/utils/post_utils.js
  test/utils/post_utils.test.js
Labels: 2: Dev Review

#664 Add the deleteBrandImage action
  src/action_types/admin.js
  src/actions/admin.js
  src/client/client4.js
  src/reducers/requests/admin.js
  test/actions/admin.test.js
Labels: Hacktoberfest

#612 add getChannelTimezone to redux
  src/action_types/channels.js
  src/actions/channels.js
  src/client/client4.js
  src/reducers/requests/channels.js
  src/store/initial_state.js
  src/types/requests.js
  test/actions/channels.test.js
Labels: 3: Ready to Merge

#679 MM-12135: Export getMissingChannelsFromPosts action.
  src/actions/search.js
Labels: 3: Ready to Merge, CherryPickApproved

#669 MM-11042: Migrate to Flow file src/actions/users.js in mattermost-redux
  src/actions/helpers.js
  src/actions/roles.js
  src/actions/users.js
Labels: 3: Ready to Merge, Hacktoberfest

#684 MM-12792 Add channel map selectors for arbirtrary teams
  src/selectors/entities/channels.js
  test/selectors/channels.test.js
Labels: 3: Ready to Merge

#686 [MM-12809] Add default options for Client4.autocompleteUsers
  src/actions/users.js
  src/client/client4.js
  src/constants/general.js
Labels: 2: Dev Review

#692 MM-12815: TIdy up usage of advanced permissions deprecated configs.
  src/utils/channel_utils.js
  src/utils/post_utils.js
Labels: 2: Dev Review

#689 MM-12827 Populate emoji and file state from post metadata
  src/actions/posts.js
  src/reducers/entities/emojis.js
  src/reducers/entities/files.js
  src/reducers/entities/posts.js
  src/types/posts.js
  src/types/reactions.js
  test/actions/posts.test.js
  test/reducers/entities/emojis.test.js
  test/reducers/entities/files.test.js
  test/reducers/entities/posts.test.js
Labels: 3: Ready to Merge

#691 MM-12827/MM-12828 Populate reactions from post metadata
  src/reducers/entities/posts.js
  test/reducers/entities/posts.test.js
Labels: 3: Ready to Merge
