Repository mattermost/mattermost-redux, pull requests merged in 2018-04, with the labels that each got.

#451 MM-9792 Do not auto close DM if it is being viewed
  src/selectors/entities/channels.js
  src/utils/channel_utils.js
  test/utils/channel_utils.test.js
Labels: 3: Ready to Merge

#453 MM-10010: skip logging 404s on missing custom emoji
  src/actions/emojis.js
Labels: 2: Dev Review

#454 Fix postsInThread being reset to null when getPostsSince(...) returns empty list
  src/reducers/entities/posts.js
Labels: 2: Dev Review

#433 Migrating some files (constants/action_types) to flow and the actions/admin.js
  src/action_types/admin.js
  src/action_types/alerts.js
  src/action_types/channels.js
  src/action_types/emojis.js
  src/action_types/errors.js
  src/action_types/files.js
  src/action_types/general.js
  src/action_types/index.js
  src/action_types/integrations.js
  src/action_types/jobs.js
  src/action_types/posts.js
  src/action_types/preferences.js
  src/action_types/search.js
  src/action_types/teams.js
  src/action_types/users.js
  src/actions/admin.js
  src/constants/alerts.js
  src/constants/emoji.js
  src/constants/files.js
  src/constants/general.js
  src/constants/index.js
  src/constants/permissions.js
  src/constants/posts.js
  src/constants/preferences.js
  src/constants/request_status.js
  src/constants/stats.js
  src/constants/teams.js
  src/constants/websocket.js
  src/reducers/requests/files.js
  src/store/initial_state.js
  src/types/jobs.js
  src/types/store.js
  src/utils/user_utils.js
Labels: 3: Ready to Merge

#455 Add missing getState on forceLogoutIfNecessary
  src/actions/channels.js
  src/actions/teams.js
  src/actions/users.js
Labels: 3: Ready to Merge

#458 MM-9831: expose getProfiles for use in the admin console
  src/selectors/entities/users.js
  test/selectors/users.test.js
Labels: 3: Ready to Merge

#457 MM-10136: Not allowing to edit others posts in the interface
  src/utils/post_utils.js
  test/utils/post_utils.test.js
Labels: 3: Ready to Merge

#459 Flagged posts and recent mentions
  src/action_types/search.js
  src/actions/posts.js
  src/actions/search.js
  src/actions/websocket.js
  src/client/client4.js
  src/reducers/entities/posts.js
  src/reducers/entities/search.js
  src/reducers/requests/search.js
Labels: 3: Ready to Merge

#462 Adds initial request state to roles.
  src/store/initial_state.js
Labels: 3: Ready to Merge

#463 Replacing hash usage with token for invitations
  src/actions/users.js
  src/client/client.js
  src/client/client4.js
Labels: 2: Dev Review, Awaiting PR

#465 Added explicit versions to all packages
  package.json
Labels: 3: Ready to Merge

#467 MM-10181: don't duplicate server errors
  src/actions/errors.js
  test/actions/errors.test.js
Labels: 3: Ready to Merge

#466 MM-8528: manage sendingPostIds and avoid double-sending
  src/actions/posts.js
  src/reducers/entities/posts.js
  src/selectors/entities/posts.js
  test/reducers/entities/posts.test.js
  test/selectors/posts.test.js
Labels: 3: Ready to Merge

#464 [GH-7775] Add Client4.convertChannelToPrivate
  src/actions/channels.js
  src/client/client4.js
  test/actions/channels.test.js
Labels: 3: Ready to Merge

#470 MM-10298: Fix channel deletion and edition permissions check
  src/utils/channel_utils.js
Labels: 3: Ready to Merge

#471 Make getJoinableTeams return a sorted array of teams
  src/selectors/entities/teams.js
  test/selectors/teams.test.js
Labels: 3: Ready to Merge

#472 Fix npm run dev commands
  package.json
Labels: 2: Dev Review

#473 MM-9849 Added ability to get environment config
  src/action_types/admin.js
  src/actions/admin.js
  src/client/client4.js
  src/reducers/entities/admin.js
  src/reducers/requests/admin.js
  src/selectors/entities/admin.js
  src/store/initial_state.js
  test/actions/admin.test.js
Labels: 3: Ready to Merge

#474 [MM-10354] Add request for Client4.removeTeamIcon
  src/action_types/teams.js
  src/actions/teams.js
  src/client/client4.js
  src/reducers/requests/teams.js
  test/actions/teams.test.js
Labels: 2: Dev Review
