Repository mattermost/mattermost-redux, pull requests merged in 2018-06, with the labels that each got.

#515 MM-9547 Added selector for CustomUrlSchemes setting
  src/constants/general.js
  src/selectors/entities/general.js
  test/selectors/general.test.js
Labels: 3: Ready to Merge

#517 MM-10758: Remove v3 api client code
  src/actions/emojis.js
  src/actions/general.js
  src/actions/teams.js
  src/actions/users.js
  src/client/client.js
  src/client/index.js
  test/actions/general.test.js
Labels: 2: Dev Review

#518 Preparing last details for start the flow campaign
  Makefile
  PULL_REQUEST_TEMPLATE.md
  src/action_types/roles.js
  src/actions/schemes.js
  src/client/index.js
  src/reducers/entities/index.js
  src/reducers/index.js
  src/reducers/requests/index.js
  src/reducers/requests/roles.js
  src/store/index.js
  src/types/actions.js
  src/types/admin.js
  src/types/channels.js
  src/types/emojis.js
  src/types/files.js
  src/types/general.js
  src/types/integrations.js
  src/types/jobs.js
  src/types/posts.js
  src/types/requests.js
  src/types/schemes.js
  src/types/search.js
  src/types/store.js
  src/types/teams.js
  src/types/users.js
Labels: 3: Ready to Merge

#521 MM-10776: Adds support for new API endpoint to update team or channel…
  src/action_types/channels.js
  src/action_types/teams.js
  src/actions/channels.js
  src/actions/teams.js
  src/client/client4.js
  src/reducers/entities/channels.js
  src/reducers/entities/teams.js
  src/reducers/requests/channels.js
  src/reducers/requests/teams.js
  src/store/initial_state.js
  src/types/requests.js
  test/actions/channels.test.js
Labels: 3: Ready to Merge, Awaiting Submitter Action

#520 Migrate typing to flow
  src/reducers/entities/typing.js
  src/selectors/entities/typing.js
  src/types/store.js
  src/types/typing.js
Labels: 3: Ready to Merge

#522 Disable fetch calls when offline
  src/client/client4.js
  src/store/configureStore.dev.js
  src/store/configureStore.prod.js
Labels: 3: Ready to Merge

#523 [MM-10519] Fix permission error on channel_converted event (in used by mobile RN)
  src/actions/websocket.js
Labels: 3: Ready to Merge

#524 Relese5.0 merge master 20180608
  src/action_types/channels.js
  src/action_types/teams.js
  src/actions/channels.js
  src/actions/teams.js
  src/actions/websocket.js
  src/client/client4.js
  src/reducers/entities/channels.js
  src/reducers/entities/teams.js
  src/reducers/requests/channels.js
  src/reducers/requests/teams.js
  src/store/configureStore.dev.js
  src/store/configureStore.prod.js
  src/store/initial_state.js
  src/types/requests.js
  test/actions/channels.test.js
Labels: 3: Ready to Merge

#525 Warn less often about backwards compatibility
  src/utils/helpers.js
Labels: 3: Ready to Merge

#526 s/cheking/checking/
  PULL_REQUEST_TEMPLATE.md
Labels: 3: Ready to Merge

#529 Relese5.0 merge master 20180611
  src/actions/roles.js
  src/store/initial_state.js
  src/utils/helpers.js
Labels: 3: Ready to Merge

#530 MM-10763 and MM-10874: Not load remove-redux-devtools on tests
  src/store/configureStore.dev.js
Labels: 3: Ready to Merge

#532 MM-10888 Filter out combined system messages not mentioning current user
  src/selectors/entities/posts.js
  src/utils/post_utils.js
  test/utils/post_utils.test.js
Labels: 3: Ready to Merge

#533 Disables ESLint 'complexity' rule.
  .eslintrc.json
Labels: 2: Dev Review

#534 Release 5.0 merge to master 20180614
  src/selectors/entities/posts.js
  src/store/configureStore.dev.js
  src/utils/post_utils.js
  test/utils/post_utils.test.js
Labels: 2: Dev Review

#536 Fix make bundle command
  README.md
  webpack.config.js
Labels: 2: Dev Review

#528 Add initial JenkinsFile for redux
  .eslintignore
  build/Jenkinsfile
Labels: 3: Ready to Merge

#537 fix jenkinspipeline
  build/Jenkinsfile
Labels: 2: Dev Review

#538 Add makeGetProfilesByIdsAndUsernames selector
  src/selectors/entities/users.js
  test/selectors/users.test.js
Labels: 3: Ready to Merge

#540 add makeGetProfilesByIdsAndUsernames (#538)
  src/selectors/entities/users.js
  test/selectors/users.test.js
Labels: 2: Dev Review

#542 [MM-10929] Only consider adding user to a list when addedUserId is available
  src/utils/post_utils.js
  test/utils/post_utils.test.js
Labels: 2: Dev Review

#541 MM-6988 Added getSearchMatches selector
  src/reducers/entities/search.js
  src/selectors/entities/posts.js
  test/reducers/entities/search.test.js
Labels: 3: Ready to Merge

#539 MM-10902 Add reducer registry to allow dynamically adding reducers
  src/store/configureStore.dev.js
  src/store/configureStore.prod.js
  src/store/helpers.js
  src/store/reducer_registry.js
  test/store/reducer_registry.test.js
Labels: 3: Ready to Merge

#543 Prevent "Invalid or expired session" errors from being added the error store
  src/actions/errors.js
  test/actions/errors.test.js
Labels: 2: Dev Review

#548 Silence fetch errors caused by websocket action
  src/actions/websocket.js
Labels: 2: Dev Review

#547 remove stage with live server tests
  build/Jenkinsfile
Labels: 2: Dev Review

#508 Get the total count of system users from the api endpoint /users/stats
  src/action_types/users.js
  src/actions/users.js
  src/client/client4.js
  src/reducers/entities/users.js
  src/reducers/requests/users.js
  src/selectors/entities/users.js
  src/store/initial_state.js
  src/types/users.js
  test/actions/users.test.js
Labels: 3: Ready to Merge

#550 MM-11016 Prevent error when failing to parse websocket origin
  src/client/websocket_client.js
Labels: 3: Ready to Merge

#551 MM-11016 Prevent error when failing to parse websocket origin
  src/client/websocket_client.js
Labels: 3: Ready to Merge

#553 MM-10996 Fixed getting post thread after receiving posts over the websocket (1.9.2)
  src/actions/websocket.js
Labels: 3: Ready to Merge

#552 MM-10996 Fixed getting post thread after receiving posts over the websocket
  src/actions/websocket.js
Labels: 3: Ready to Merge

#544 Gfycat integration
  src/action_types/gifs.js
  src/action_types/index.js
  src/actions/gifs.js
  src/reducers/entities/gifs.js
  src/reducers/entities/index.js
  src/store/initial_state.js
  src/utils/gfycat-sdk.umd.bundle.min.js
  src/utils/gfycatSdk.js
Labels: 2: Dev Review
