Repository mattermost/mattermost-redux, pull requests merged in 2018-12, with the labels that each got.

#726 MM-13209: add makeGetProfilesNotInChannel selector
  src/selectors/entities/users.js
  test/selectors/users.test.js
Labels: 3: Ready to Merge, CherryPickApproved

#728 MM-13195: Enforce at least one load of roles for the initial load
  src/actions/roles.js
Labels: 3: Ready to Merge

#733 Sort pinned posts from newest to oldest
  src/action_types/search.js
  src/actions/search.js
  src/reducers/entities/search.js
Labels: 3: Ready to Merge, CherryPickApproved

#734 [MM-13398] Fix sorting of channels at sidebar unreads section
  src/selectors/entities/channels.js
  test/selectors/channels.test.js
Labels: 2: Dev Review, CherryPickApproved

#732 MM-8662: Added `force` flag to uploadPlugin methods
  src/actions/admin.js
  src/client/client4.js
  test/actions/admin.test.js
Labels: 2: Dev Review

#737 MM-13243: Don't return custom emoji if the server config has custom e…
  src/selectors/entities/emojis.js
Labels: 3: Ready to Merge

#731 MM-13077 Remove participant is typing as soon as the post arrives
  src/actions/websocket.js
Labels: 3: Ready to Merge, CherryPickApproved

#738 [MM-13323] Update dev dependency mock-socket to 8.0.5
  package-lock.json
  package.json
  test/actions/websocket.test.js
Labels: 2: Dev Review

#740 MM-13444 Fix IE11 support.
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#741 [MM-13433] Performance: return an object from store or null for makeGetReactionsForPost selector
  src/selectors/entities/posts.js
  test/selectors/posts.test.js
Labels: 3: Ready to Merge

#739 MM-8662: Removed RECEIVED_PLUGIN action type
  src/action_types/admin.js
  src/actions/admin.js
  src/reducers/entities/admin.js
  test/actions/admin.test.js
  test/reducers/entities/admin.test.js
Labels: 2: Dev Review

#743 [MM-13434] Add makeGetDisplayName selector
  src/selectors/entities/users.js
  test/selectors/users.test.js
Labels: 3: Ready to Merge
