Repository mattermost/mattermost-redux, pull requests merged in 2018-11, with the labels that each got.

#690 MM-12687 Shallow clone data to avoid state mutation in analytics reducer
  src/reducers/entities/admin.js
  test/reducers/entities/admin.test.js
Labels: 3: Ready to Merge

#701 MM-12841 Fix for mention channel ordering with unread channels
  src/selectors/entities/channels.js
  test/selectors/channels.test.js
Labels: 3: Ready to Merge, CherryPickApproved

#688 [MM-12409] Make re-acceptance interval configurable instead of hard-coded to 12 months
  src/action_types/users.js
  src/actions/users.js
  src/client/client4.js
  src/reducers/entities/users.js
  src/reducers/requests/users.js
  src/selectors/entities/users.js
  src/store/initial_state.js
  src/types/requests.js
  src/types/users.js
  test/actions/users.test.js
  test/selectors/users.test.js
Labels: 3: Ready to Merge

#696 Update NOTICE.txt
  NOTICE.txt
Labels: 3: Ready to Merge

#579 Upgrade to babel 7
  .babelrc
  babel.config.js
  package-lock.json
  package.json
  test/mocha.opts
  test/setup.js
  webpack.config.js
Labels: 2: Dev Review

#702 MM-12874 Store OpenGraph metadata in correct part of store
  src/reducers/entities/posts.js
  test/reducers/entities/posts.test.js
Labels: 3: Ready to Merge

#695 Adding channels flow annotations
  src/actions/channels.js
  src/types/channels.js
Labels: 3: Ready to Merge, Hacktoberfest

#704 MM-11477 Wrap objects thrown by Client4 in a proper error type
  src/client/client4.js
  src/reducers/requests/helpers.js
  src/utils/sentry.js
  test/actions/helpers.test.js
  test/test_store.js
  test/utils/sentry.test.js
Labels: 3: Ready to Merge, CherryPickApproved

#698 MM-11047 Migrate errors action file to Flow
  src/actions/errors.js
  src/types/actions.js
  src/types/errors.js
Labels: 2: Dev Review, Hacktoberfest

#708 MM-13020 Revert "MM-11477 Wrap objects thrown by Client4 in a proper error type (#704)" (5.5)
  src/client/client4.js
  src/reducers/requests/helpers.js
  src/utils/sentry.js
  test/actions/helpers.test.js
  test/test_store.js
  test/utils/sentry.test.js
Labels: 3: Ready to Merge

#685 fix default language import
  src/selectors/entities/i18n.js
  src/selectors/entities/teams.js
  src/utils/file_utils.js
Labels: 3: Ready to Merge, Hacktoberfest

#712 Fix fetchMyChannelsAndMembers error handler
  src/actions/channels.js
Labels: 2: Dev Review

#710 MM-12844/MM-13001 Add interactive dialog actions
  src/action_types/integrations.js
  src/actions/integrations.js
  src/actions/posts.js
  src/actions/websocket.js
  src/client/client4.js
  src/constants/websocket.js
  src/reducers/entities/integrations.js
  src/reducers/requests/integrations.js
  src/types/integrations.js
  src/utils/integration_utils.js
  test/actions/integrations.test.js
  test/actions/websocket.test.js
  test/utils/integration_utils.test.js
Labels: 2: Dev Review, Awaiting PR

#709 MM-13020 Make ClientError.message enumerable
  src/client/client4.js
  test/client/client4.test.js
Labels: 3: Ready to Merge

#713 MM-12755 Add selector for isCommentMention
  src/selectors/entities/posts.js
  src/utils/post_utils.js
  test/selectors/posts.test.js
  test/utils/post_utils.test.js
Labels: 2: Dev Review

#711 WebSocket actions improvement
  src/actions/websocket.js
  src/client/websocket_client.js
  test/actions/websocket.test.js
Labels: 3: Ready to Merge

#718 Action and reducers for pinned posts
  src/action_types/search.js
  src/actions/search.js
  src/reducers/entities/search.js
  src/reducers/requests/search.js
Labels: 3: Ready to Merge

#715 MM-12233: update profiles in/not in channel on ws
  src/action_types/channels.js
  src/actions/websocket.js
  src/reducers/entities/users.js
  test/reducers/entities/users.test.js
Labels: 3: Ready to Merge

#714 Fix more DM's modal
  src/selectors/entities/channels.js
  test/selectors/channels.test.js
Labels: 2: Dev Review

#717 MM-12839: Remove archived channels posts from search results when needed
  src/actions/channels.js
  src/actions/websocket.js
  src/reducers/entities/posts.js
  test/actions/websocket.test.js
  test/reducers/entities/posts.test.js
Labels: 2: Dev Review

#721 Scrolling Overhaul: Add metadata to posts returned by the server
  src/actions/posts.js
  src/reducers/entities/emojis.js
  src/reducers/entities/files.js
  src/reducers/entities/posts.js
  src/types/posts.js
  src/types/reactions.js
  test/actions/posts.test.js
  test/reducers/entities/emojis.test.js
  test/reducers/entities/files.test.js
  test/reducers/entities/posts.test.js
Labels: 3: Ready to Merge

#697 [MM-8404] Add an utility function to ignore channel-wide mentions on channels
  src/constants/index.js
  src/constants/users.js
  src/utils/channel_utils.js
  test/utils/channel_utils.test.js
Labels: 2: Dev Review, Hacktoberfest

#723 MM-12400: Call get my terms of service only if the terms of service feature is enabled
  src/actions/users.js
Labels: 3: Ready to Merge, CherryPickApproved

#722 MM-12574 Track events for interactive messages and dialogs
  src/client/client4.js
Labels: 3: Ready to Merge, CherryPickApproved

#725 [MM-13175] Only put channels on top of the sorted list for unread channels group
  src/selectors/entities/channels.js
  test/selectors/channels.test.js
Labels: CherryPickApproved

#727 Fix handleNewPostEvent for replies
  src/actions/websocket.js
Labels: CherryPickApproved
