Repository mattermost/mattermost-redux, pull requests merged in 2018-09, with the labels that each got.

#618 [MM-11717] Exclude deleted users from favourites list
  src/selectors/entities/channels.js
  test/selectors/channels.test.js
  test/test_helper.js
Labels: 3: Ready to Merge

#622 Merge release-5.3-20180903124818
  src/selectors/entities/channels.js
  test/selectors/channels.test.js
  test/test_helper.js
Labels: 2: Dev Review

#623 MM-11924 Preventing editing of pending and failed posts.
  src/selectors/entities/posts.js
  test/selectors/posts.test.js
Labels: 3: Ready to Merge

#626 Fix when opengraph returns null
  src/actions/posts.js
  test/actions/posts.test.js
Labels: 3: Ready to Merge

#627 MM-11704 Fix emoji reactions on subpath install.
  src/utils/emoji_utils.js
Labels: 2: Dev Review, 3: Ready to Merge

#625 [MM-11971] Fix post type comparison
  src/utils/post_utils.js
  test/utils/post_utils.test.js
Labels: 3: Ready to Merge

#630 Merge release-5.3-20180910141323
  src/actions/posts.js
  src/selectors/entities/posts.js
  src/utils/emoji_utils.js
  src/utils/post_utils.js
  test/actions/posts.test.js
  test/selectors/posts.test.js
  test/utils/post_utils.test.js
Labels: 2: Dev Review

#621 MM-11725: Adding new search_autocomplete channels api
  src/actions/channels.js
  src/client/client4.js
  test/actions/channels.test.js
Labels: 3: Ready to Merge

#633 Merge release-5.3-20180912130737
  src/actions/general.js
  src/reducers/requests/general.js
  src/selectors/entities/general.js
  src/store/initial_state.js
  test/actions/general.test.js
Labels: 2: Dev Review

#628 [MM-11282] Add selector to get channel by name
  src/selectors/entities/channels.js
  test/selectors/channels.test.js
Labels: 3: Ready to Merge

#634 [MM-11974] Change default return string for channel displayname
  src/utils/channel_utils.js
Labels: 3: Ready to Merge

#635 Run babel on 'npm install' and remove .npminstall
  Makefile
  package.json
Labels: 3: Ready to Merge

#640 MM-11776 Hard code prepackaged plugins
  src/constants/index.js
  src/constants/plugins.js
  src/reducers/entities/admin.js
Labels: 3: Ready to Merge

#639 Fix package.json problems
  package.json
Labels: 3: Ready to Merge

#638 bump package version to 5.3.1
  package.json
Labels: 3: Ready to Merge

#645 Switch getPostIdsInChannel to not be a selector
  src/selectors/entities/posts.js
Labels: 3: Ready to Merge

#647 Fix "{yyyy} {name of copyright owner}" in LICENSE.txt
  LICENSE.txt
Labels: 2: Dev Review

#643 MM-12027 Adding paging for elasticsearch results.
  src/actions/search.js
  src/client/client4.js
  src/reducers/entities/search.js
  test/actions/search.test.js
Labels: 2: Dev Review

#648 MM-11577: Do not redirect to default channel on delete if archived channels are enabled
  src/actions/channels.js
  src/actions/websocket.js
Labels: 2: Dev Review

#650 Remove unnecessary event emitter when server version changes
  src/client/client4.js
Labels: 3: Ready to Merge

#644 [MM-11959] Add Preferences constants of ADVANCED_SEND_ON_CTRL_ENTER and ADVANCED_CODE_BLOCK_ON_CTRL_ENTER
  src/constants/preferences.js
Labels: 2: Dev Review

#657 Fixing other search types.
  src/reducers/entities/search.js
Labels: 3: Ready to Merge
