Repository mattermost/mattermost-redux, pull requests merged in 2018-05, with the labels that each got.

#461 MM-8786: Adds Schemes.
  src/action_types/index.js
  src/action_types/schemes.js
  src/actions/schemes.js
  src/client/client4.js
  src/constants/schemes.js
  src/reducers/entities/channels.js
  src/reducers/entities/index.js
  src/reducers/entities/schemes.js
  src/reducers/entities/teams.js
  src/reducers/requests/index.js
  src/reducers/requests/schemes.js
  src/selectors/entities/schemes.js
  src/store/initial_state.js
  src/types/channels.js
  src/types/schemes.js
  src/types/store.js
  src/types/teams.js
  test/actions/roles.test.js
  test/actions/schemes.test.js
  test/selectors/schemes.test.js
  test/test_helper.js
Labels: 2: Dev Review

#477 Remove dependency with security issue
  package-lock.json
  package.json
  test/mocha.opts
  test/setup.js
Labels: 3: Ready to Merge

#481 Added getCurrentUserLocale selector
  src/constants/general.js
  src/selectors/entities/channels.js
  src/selectors/entities/i18n.js
  src/selectors/entities/teams.js
  src/utils/channel_utils.js
  test/selectors/i18n.test.js
  test/test_helper.js
Labels: 2: Dev Review

#482 MM-10464: Handle all cases display username
  src/utils/user_utils.js
  test/utils/user_utils.test.js
Labels: 2: Dev Review

#483 MM-10432: Don't access roles before they're loaded.
  src/selectors/entities/roles.js
  test/selectors/roles.test.js
Labels: 3: Ready to Merge

#485 [MM-10215] Add utility function and constant to fix email notification issue on mobile RN
  src/constants/preferences.js
  src/utils/notify_props.js
  test/utils/notify_props.test.js
Labels: 2: Dev Review

#486 Updated flow-typed version and added npm commands
  package.json
Labels: 2: Dev Review

#487 Fix flow errors raised from `npm run flow`
  src/selectors/entities/common.js
  src/selectors/entities/general.js
  src/utils/i18n_utils.js
  src/utils/user_utils.js
Labels: 2: Dev Review

#488 Flow type definitions added to alerts
  src/actions/alerts.js
  src/reducers/entities/alerts.js
  src/selectors/entities/alerts.js
  src/types/alerts.js
  src/types/store.js
Labels: 2: Dev Review

#490 MM-8622: Improved plugin error reporting
  src/action_types/admin.js
  src/actions/admin.js
  src/actions/websocket.js
  src/client/client4.js
  src/constants/plugins.js
  src/constants/websocket.js
  src/reducers/entities/admin.js
  src/reducers/requests/admin.js
  test/actions/admin.test.js
  test/reducers/entities/admin.test.js
Labels: 3: Ready to Merge

#495 Prevent duplicate flagged posts
  src/reducers/entities/search.js
Labels: 3: Ready to Merge

#480 MM-10454: Removing Set usage in store for roles
  src/actions/roles.js
  src/store/initial_state.js
Labels: 3: Ready to Merge

#456 [MM-3996] Improved (add/join/leave/remove from channel/team) system messages
  src/actions/posts.js
  src/constants/posts.js
  src/reducers/entities/posts.js
  src/utils/helpers.js
  src/utils/post_utils.js
  src/utils/user_utils.js
  test/test_helper.js
  test/utils/post_utils.test.js
Labels: 2: Dev Review

#498 MM-8622: s/cluster_discovery/cluster/
  src/reducers/entities/admin.js
  test/reducers/entities/admin.test.js
Labels: 2: Dev Review

#499 [MM-10455] Include "id" to data for UserTypes actions - RECEIVED_PROFILE_(NOT)_IN_TEAM / RECEIVED_PROFILE_(NOT)_IN_CHANNEL
  src/actions/channels.js
  src/actions/teams.js
  src/reducers/entities/users.js
  test/actions/websocket.test.js
Labels: 3: Ready to Merge

#489 Adding jobs flow annotations
  src/actions/jobs.js
  src/reducers/entities/jobs.js
  src/selectors/entities/jobs.js
Labels: 2: Dev Review

#504 Fix combined posts which ignores custom and other post types
  src/utils/post_utils.js
  test/utils/post_utils.test.js
Labels: 3: Ready to Merge

#503 Upgrading dependencies.
  package-lock.json
  package.json
  src/actions/errors.js
  src/client/fetch_etag.js
  src/reducers/entities/admin.js
  src/reducers/entities/users.js
  src/selectors/entities/channels.js
  src/store/configureStore.dev.js
  src/types/store.js
  src/utils/channel_utils.js
  test/actions/general.test.js
  test/actions/integrations.test.js
  test/actions/search.test.js
  test/actions/users.test.js
  test/mocha.opts
  test/utils/post_utils.test.js
Labels: 3: Ready to Merge

#505 MM-10666: ignore unknown profiles in `sortAndInjectProfiles`
  src/selectors/entities/users.js
Labels: 2: Dev Review

#500 CBA Support
  src/actions/general.js
  src/actions/websocket.js
  src/client/websocket_client.js
Labels: 3: Ready to Merge

#493 [MM-10430] Add selector to check if the channel is hidden
  src/selectors/entities/channels.js
Labels: 3: Ready to Merge, Awaiting PR

#510 MM-8789: Add search teams endpoint and action
  src/action_types/schemes.js
  src/actions/schemes.js
  src/actions/teams.js
  src/client/client4.js
  src/constants/schemes.js
  src/reducers/entities/schemes.js
  src/reducers/requests/schemes.js
  src/selectors/entities/schemes.js
  src/types/schemes.js
  src/types/store.js
  test/actions/schemes.test.js
  test/selectors/schemes.test.js
Labels: 3: Ready to Merge

#513 MM-8853: Add manage_emojis permissions
  src/constants/permissions.js
Labels: 2: Dev Review
