Repository mattermost/mattermost-redux, pull requests merged in 2018-07, with the labels that each got.

#555 Fix flow errors
  src/types/requests.js
  src/types/store.js
Labels: 3: Ready to Merge

#558 Add email regex for validation
  src/utils/helpers.js
  test/utils/helpers.test.js
Labels: 3: Ready to Merge

#561 GH-8994 added flow assertions to roles js
  src/actions/roles.js
  src/types/roles.js
  src/types/store.js
Labels: 3: Ready to Merge

#559 If the websocket url is malformed do not attempt to connect
  src/client/websocket_client.js
Labels: 3: Ready to Merge

#562 GH-8993 added flow types to files js
  src/actions/files.js
Labels: 3: Ready to Merge

#565 Release 5.1 daily merge 20180710
  src/client/websocket_client.js
Labels: 2: Dev Review

#560 GH-8995 added the flow types for timezone js
  src/actions/timezone.js
Labels: 2: Dev Review

#568 Migrate actions/helpers.js to flow
  src/actions/helpers.js
  src/types/errors.js
Labels: 2: Dev Review

#575 MM-11362 Update config in redux state when enabling/disabling plugins
  src/reducers/entities/admin.js
Labels: 3: Ready to Merge

#573 MM-11070: Adds post ID filter selector.
  src/selectors/entities/channels.js
  test/selectors/channels.test.js
Labels: 3: Ready to Merge

#574 MM-11310: Add getUnreadPosts
  src/action_types/posts.js
  src/actions/posts.js
  src/client/client4.js
  src/reducers/requests/posts.js
  src/store/initial_state.js
  src/types/requests.js
  test/actions/posts.test.js
Labels: 3: Ready to Merge, Awaiting PR

#572 Add types to actions/general.js
  src/actions/general.js
  src/actions/helpers.js
  src/actions/roles.js
  src/types/actions.js
  src/types/client4.js
  src/utils/key_mirror.js
Labels: 2: Dev Review

#578 Improve typing of action types and fix related bugs
  src/action_types/channels.js
  src/action_types/teams.js
  src/reducers/requests/teams.js
  src/utils/key_mirror.js
Labels: 2: Dev Review

#582 [MM-10621] Sort fileInfos by "create_at" (if not created at the same time) or by "name"
  src/selectors/entities/files.js
  src/utils/file_utils.js
  test/utils/file_utils.test.js
Labels: 2: Dev Review

#556 MM-11066: Allow to get channels when are deleted
  src/actions/channels.js
  src/actions/search.js
  src/client/client4.js
  test/actions/channels.test.js
  test/actions/search.test.js
Labels: 3: Ready to Merge, Awaiting PR

#583 [MM-10918] Add actor ID to props of system_remove_channel combined message
  src/utils/post_utils.js
  test/utils/post_utils.test.js
Labels: 2: Dev Review
