Repository mattermost/mattermost-redux, pull requests merged in 2018-08, with the labels that each got.

#584 MM-11530: When the channel is archived mustn't be delete from the store
  src/reducers/entities/channels.js
  test/actions/channels.test.js
Labels: 3: Ready to Merge

#585 [MM-11051]: Add new param to displayUsername to circumvent defaultName
  src/selectors/entities/typing.js
  src/utils/user_utils.js
  test/utils/user_utils.test.js
Labels: 3: Ready to Merge

#587 Remove backwards compatibility warnings
  src/utils/helpers.js
Labels: 3: Ready to Merge

#589 Revert "New selectors for sidebar reorganization (#549)"
  src/constants/general.js
  src/selectors/entities/channels.js
  src/selectors/entities/sidebar.js
  src/utils/channel_utils.js
  test/selectors/channels.test.js
Labels: 3: Ready to Merge

#591 MM-11510: Fixes for the handling of channel deletions.
  src/actions/channels.js
  src/actions/websocket.js
  src/reducers/entities/channels.js
  test/actions/channels.test.js
Labels: 2: Dev Review

#592 Jenkins build improvements
  build/.gitignore
  build/Jenkinsfile
  package-lock.json
  package.json
  test/mocha-multi-reporters-config.json
  test/mocha.opts
Labels: 2: Dev Review

#588 MM-11484 Add check for undefined channel objects
  src/selectors/entities/channels.js
Labels: 3: Ready to Merge

#590 MM-11556: introduce a getDirectAndGroupChannels
  src/selectors/entities/channels.js
  test/selectors/channels.test.js
Labels: 3: Ready to Merge

#596 MM-11576: Fixed join to archived channel by clicking link
  src/actions/channels.js
  test/actions/channels.test.js
Labels: 3: Ready to Merge

#598 Release 5.2 daily merge 20180810
  src/actions/channels.js
  src/selectors/entities/channels.js
  test/actions/channels.test.js
  test/selectors/channels.test.js
Labels: 2: Dev Review

#599 Merging master into release-5.2 (For include last changes on mobile)
  build/.gitignore
  build/Jenkinsfile
  package-lock.json
  package.json
  src/client/client4.js
  src/selectors/entities/channels.js
  test/mocha-multi-reporters-config.json
  test/mocha.opts
Labels: 3: Ready to Merge

#603 MM-11510: Only return archived channel if it's the current channel.
  src/selectors/entities/channels.js
Labels: 2: Dev Review

#604 MM-11510: Only return archived channel if it's the current channel. (…
  src/selectors/entities/channels.js
Labels: 3: Ready to Merge

#605 [MM-11170] Fix unreads for deleted users
  src/selectors/entities/channels.js
  test/selectors/channels.test.js
  test/test_helper.js
Labels: 2: Dev Review

#607 Merge release-5.2-20180816094050
  src/selectors/entities/channels.js
  test/selectors/channels.test.js
  test/test_helper.js
Labels: 2: Dev Review

#577 MM-11223: Add backup, clear and restore logic for postsInChannel
  src/action_types/posts.js
  src/actions/posts.js
  src/reducers/entities/posts.js
  src/selectors/entities/posts.js
  src/store/initial_state.js
  src/types/posts.js
  src/utils/post_utils.js
  test/actions/posts.test.js
  test/reducers/entities/posts.test.js
  test/utils/post_utils.test.js
Labels: 3: Ready to Merge

#611 MM-11786: Adds getRedirectLocation.
  src/action_types/general.js
  src/actions/general.js
  src/client/client4.js
  test/actions/general.test.js
Labels: 3: Ready to Merge, Awaiting PR

#615 Feature/search after before on
  src/actions/search.js
  src/client/client4.js
Labels: 2: Dev Review

#617 MM-11696 Factor out marking GMs open to a separate action
  src/actions/channels.js
  test/actions/channels.test.js
Labels: 2: Dev Review

#614 [MM-11279] Selector for User Audits
  src/selectors/entities/users.js
  test/selectors/users.test.js
Labels: 3: Ready to Merge

#619 MM-11449 Show OpenGraph previews for pages with any of the required fields
  src/actions/posts.js
Labels: 3: Ready to Merge
