Repository mattermost/mattermost-redux, pull requests merged in 2019-05, with the labels that each got.

#824 Remove outdated information from contributing file
  CONTRIBUTING.md
Labels: 2: Dev Review

#826 Fixes RN master branch build
  babel.config.js
  package-lock.json
  package.json
Labels: 3: Reviews Complete

#823 Migrate a few OAuth actions from webapp
  src/action_types/integrations.js
  src/actions/integrations.js
  src/actions/integrations.test.js
Labels: 3: Reviews Complete

#829 [MM-13955] Add getLastPostIndex
  src/utils/post_list.js
  src/utils/post_list.test.js
Labels: 3: Reviews Complete

#825 MM-15363 Properly generate GM display name
  src/selectors/entities/channels.js
  src/utils/channel_utils.js
Labels: 3: Reviews Complete

#811 MM-14977 Add empty metadata obj to system messages
  src/utils/post_list.js
  src/utils/post_list.test.js
Labels: 3: Reviews Complete

#821 MM-14410: Adds ability to retrieve groups that are associated (or not-associated) to teams.
  src/action_types/groups.js
  src/actions/groups.js
  src/actions/groups.test.js
  src/client/client4.js
  src/reducers/entities/groups.js
  src/reducers/entities/teams.js
  src/reducers/requests/groups.js
  src/selectors/entities/groups.js
  src/selectors/entities/groups.test.js
  src/store/initial_state.js
  src/types/groups.js
  src/types/requests.js
  src/types/teams.js
Labels: 3: Reviews Complete, Do Not Merge/Awaiting PR

#831 MM-14295 - Add "user_actual_role" field to client-side diagnostics to track if a user is a System Admin
  src/actions/users.js
  src/client/client4.js
Labels: 2: Dev Review

#832 MM-15532 properly mark channel as read when reading the channel in another client
  src/actions/websocket.js
Labels: 3: Reviews Complete, CherryPick/Approved

#827 MM-14897: Changes to be able to add and remove groups from channels.
  package-lock.json
  src/action_types/groups.js
  src/actions/groups.js
  src/actions/groups.test.js
  src/client/client4.js
  src/reducers/entities/channels.js
  src/reducers/entities/groups.js
  src/reducers/requests/groups.js
  src/selectors/entities/groups.js
  src/selectors/entities/groups.test.js
  src/store/initial_state.js
  src/types/channels.js
  src/types/requests.js
Labels: 3: Reviews Complete, Do Not Merge/Awaiting PR

#817 [MM-14751] Add group_constrained flag when getting profiles
  src/action_types/users.js
  src/actions/users.js
  src/client/client4.js
  src/reducers/entities/users.js
Labels: 3: Reviews Complete

#833 Fix select default channel
  src/actions/channels.js
  src/actions/websocket.js
Labels: 3: Reviews Complete

#834 Adding guest permissions
  src/constants/permissions.js
Labels: 2: Dev Review

#835 Send guest email invites
  src/actions/teams.js
  src/client/client4.js
Labels: 2: Dev Review

#837 MM-15422: Adds params for channels page API endpoint.
  src/actions/channels.js
  src/client/client4.js
Labels: 3: Reviews Complete, CherryPick/Candidate, Do Not Merge/Awaiting PR

#839 MM-15667 if post was removed exclude it from postsInChannel
  src/reducers/entities/posts.js
  src/reducers/entities/posts.test.js
Labels: 3: Reviews Complete, CherryPick/Approved

#843 MM-15603 Updating dependencies.
  package-lock.json
  package.json
Labels: 3: Reviews Complete

#845 MM-15904 Only set Client user and roles if user is defined
  src/actions/users.js
Labels: 3: Reviews Complete, CherryPick/Approved
