Repository mattermost/mattermost-redux, pull requests merged in 2019-04, with the labels that each got.

#800 MM-14642: Adds new field to Team and Channel types.
  src/types/channels.js
  src/types/teams.js
  src/utils/channel_utils.js
Labels: 3: Ready to Merge

#802 MM-14617 Upgrading dependencies.
  .flowconfig
  babel.config.js
  package-lock.json
  package.json
Labels: 2: Dev Review

#804 Update NOTICE.txt
  NOTICE.txt
Labels: 3: Ready to Merge, CherryPickApproved

#808 [MM-14881] Modify filterProfilesMatchingTerm to match split parts of the username
  src/constants/general.js
  src/constants/users.js
  src/utils/user_utils.js
  src/utils/user_utils.test.js
Labels: 3: Ready to Merge, CherryPickApproved

#809 [MM-14881] Replace flatMap with a reducer
  src/utils/user_utils.js
Labels: 3: Ready to Merge, CherryPickApproved

#810 Adding VIEW_MEMBERS permissions to permissions constants
  src/constants/permissions.js
Labels: 3: Ready to Merge

#805 MM-14729: discard posts on leaving channel
  src/actions/channels.test.js
  src/actions/posts.test.js
  src/reducers/entities/posts.js
  src/reducers/entities/posts.test.js
Labels: 3: Ready to Merge

#806 [MM-12396] Option to add user to a channel from the profile pop-over (permissions fix)
  src/selectors/entities/channels.js
  src/selectors/entities/channels.test.js
Labels: 3: Ready to Merge

#807 Reorganize post state and make postsInChannel into a sparse array
  src/action_types/posts.js
  src/actions/channels.js
  src/actions/posts.js
  src/actions/posts.test.js
  src/actions/search.js
  src/actions/websocket.js
  src/actions/websocket.test.js
  src/reducers/entities/files.js
  src/reducers/entities/posts.js
  src/reducers/entities/posts.test.js
  src/reducers/entities/search.js
  src/reducers/entities/search.test.js
  src/selectors/entities/channels.test.js
  src/selectors/entities/posts.js
  src/selectors/entities/posts.test.js
  src/store/initial_state.js
  src/types/posts.js
  src/utils/post_list.js
  src/utils/post_list.test.js
  src/utils/post_utils.js
  src/utils/post_utils.test.js
Labels: 2: Dev Review

#799 Creating the concept of RedirectChannel and use it before the DefaultChannel when we are redirecting the user
  src/actions/channels.js
  src/actions/websocket.js
  src/actions/websocket.test.js
  src/selectors/entities/channels.js
  src/selectors/entities/channels.test.js
Labels: 3: Ready to Merge

#812 MM-14456 Minor updates to search
  src/actions/search.js
  src/actions/search.test.js
  src/selectors/entities/search.js
  src/selectors/entities/search.test.js
Labels: 3: Ready to Merge, CherryPickApproved

#813 Replace Jenkins to use circleci
  .circleci/config.yml
  README.md
  build/Jenkinsfile
  package.json
Labels: 3: Ready to Merge

#815 [MM-14619] Remove Clien4.online and setOnline
  package.json
  src/client/client4.js
  src/store/configureStore.dev.js
  src/store/configureStore.prod.js
Labels: 3: Ready to Merge, CherryPickApproved

#803 [MM-13671] Add RegenerateTeamInviteId Action and Client Method
  src/action_types/teams.js
  src/actions/teams.js
  src/client/client4.js
Labels: 3: Ready to Merge, CherryPickApproved

#816 Add actions to save/delete theme preference
  src/actions/preferences.js
  src/actions/preferences.test.js
Labels: 3: Ready to Merge

#822 Reverting serialize-error to version 2.1.0
  package-lock.json
  package.json
Labels: 2: Dev Review
