Repository mattermost/mattermost-redux, pull requests merged in 2019-01, with the labels that each got.

#744 Transform flow types to comment, instead of copying all source
  babel.config.js
  package-lock.json
  package.json
Labels: Tests not required

#746 Upgrading flow to the last version and fixing flow errors
  .flowconfig
  package-lock.json
  package.json
  src/reducers/entities/alerts.js
  src/reducers/entities/emojis.js
  src/reducers/entities/index.js
  src/reducers/entities/jobs.js
  src/reducers/entities/schemes.js
  src/reducers/requests/admin.js
  src/reducers/requests/channels.js
  src/reducers/requests/emojis.js
  src/reducers/requests/files.js
  src/reducers/requests/general.js
  src/reducers/requests/index.js
  src/reducers/requests/integrations.js
  src/reducers/requests/jobs.js
  src/reducers/requests/posts.js
  src/reducers/requests/preferences.js
  src/reducers/requests/roles.js
  src/reducers/requests/schemes.js
  src/reducers/requests/search.js
  src/reducers/requests/teams.js
  src/reducers/requests/users.js
  src/selectors/entities/common.js
  src/selectors/entities/general.js
  src/selectors/entities/schemes.js
  src/selectors/entities/typing.js
  src/store/initial_state.js
  src/types/requests.js
  src/types/store.js
  src/utils/emoji_utils.js
Labels: 3: Ready to Merge

#748 MM-13432 Remove unused _REQUEST, _SUCCESS and _FAILURE actions
  src/action_types/channels.js
  src/action_types/emojis.js
  src/action_types/files.js
  src/action_types/posts.js
  src/action_types/teams.js
  src/action_types/users.js
  src/actions/admin.js
  src/actions/channels.js
  src/actions/emojis.js
  src/actions/files.js
  src/actions/general.js
  src/actions/helpers.js
  src/actions/integrations.js
  src/actions/jobs.js
  src/actions/posts.js
  src/actions/preferences.js
  src/actions/roles.js
  src/actions/schemes.js
  src/actions/teams.js
  src/actions/users.js
  src/reducers/entities/posts.js
  src/reducers/requests/channels.js
  src/reducers/requests/emojis.js
  src/reducers/requests/files.js
  src/reducers/requests/index.js
  src/reducers/requests/posts.js
  src/reducers/requests/teams.js
  src/reducers/requests/users.js
  src/store/initial_state.js
  src/types/actions.js
  src/types/requests.js
  src/types/store.js
  test/actions/channels.test.js
  test/actions/emojis.test.js
  test/actions/files.test.js
  test/actions/posts.test.js
  test/actions/teams.test.js
  test/actions/users.test.js
Labels: 3: Ready to Merge

#750 Migrate to some utils files to use flow
  src/types/integrations.js
  src/types/users.js
  src/utils/file_utils.js
  src/utils/gfycat_sdk.js
  src/utils/helpers.js
  src/utils/integration_utils.js
  src/utils/notify_props.js
  src/utils/timezone_utils.js
Labels: 2: Dev Review

#749 Migrating channel selectors to flow
  src/actions/channels.js
  src/reducers/entities/emojis.js
  src/reducers/entities/jobs.js
  src/selectors/entities/channels.js
  src/selectors/entities/common.js
  src/selectors/entities/emojis.js
  src/selectors/entities/jobs.js
  src/selectors/entities/typing.js
  src/types/channels.js
  src/types/integrations.js
  src/types/jobs.js
  src/types/posts.js
  src/types/users.js
  src/types/utilities.js
  src/utils/channel_utils.js
  src/utils/team_utils.js
  src/utils/user_utils.js
Labels: 3: Ready to Merge

#747 [GH-7494] Added the filters in selectors and get users request
  src/actions/users.js
  src/client/client4.js
  src/selectors/entities/users.js
  test/selectors/users.test.js
Labels: 3: Ready to Merge

#754 Removing relative imports for types
  src/actions/admin.js
  src/actions/alerts.js
  src/actions/channels.js
  src/actions/emojis.js
  src/actions/errors.js
  src/actions/files.js
  src/actions/general.js
  src/actions/helpers.js
  src/actions/integrations.js
  src/actions/jobs.js
  src/actions/preferences.js
  src/actions/roles.js
  src/actions/schemes.js
  src/actions/teams.js
  src/actions/timezone.js
  src/reducers/entities/alerts.js
  src/reducers/entities/emojis.js
  src/reducers/entities/jobs.js
  src/reducers/entities/typing.js
  src/reducers/requests/admin.js
  src/reducers/requests/channels.js
  src/reducers/requests/files.js
  src/reducers/requests/general.js
  src/reducers/requests/helpers.js
  src/reducers/requests/integrations.js
  src/reducers/requests/jobs.js
  src/reducers/requests/posts.js
  src/reducers/requests/preferences.js
  src/reducers/requests/roles.js
  src/reducers/requests/schemes.js
  src/reducers/requests/search.js
  src/reducers/requests/teams.js
  src/reducers/requests/users.js
  src/selectors/entities/alerts.js
  src/selectors/entities/channels.js
  src/selectors/entities/common.js
  src/selectors/entities/general.js
  src/selectors/entities/typing.js
  src/utils/channel_utils.js
  src/utils/emoji_utils.js
  src/utils/file_utils.js
  src/utils/integration_utils.js
  src/utils/timezone_utils.js
Labels: 3: Ready to Merge

#752 MM-13627 Fix DM and GM mention counts missing from browser tab
  src/selectors/entities/channels.js
  test/selectors/channels.test.js
Labels: 3: Ready to Merge, CherryPickApproved, DO NOT MERGE

#706 Ldap groups phase1
  package-lock.json
  src/action_types/admin.js
  src/action_types/channels.js
  src/action_types/groups.js
  src/action_types/index.js
  src/actions/admin.js
  src/actions/admin.test.js
  src/actions/channels.js
  src/actions/channels.test.js
  src/actions/groups.js
  src/actions/helpers.js
  src/client/client4.js
  src/constants/groups.js
  src/constants/index.js
  src/reducers/entities/admin.js
  src/reducers/entities/admin.test.js
  src/reducers/entities/channels.js
  src/reducers/entities/groups.js
  src/reducers/entities/index.js
  src/reducers/requests/admin.js
  src/reducers/requests/channels.js
  src/reducers/requests/groups.js
  src/reducers/requests/index.js
  src/selectors/entities/admin.js
  src/selectors/entities/groups.js
  src/store/initial_state.js
  src/types/admin.js
  src/types/groups.js
  src/types/requests.js
  src/types/store.js
  test/actions/groups.test.js
Labels: 2: Dev Review, DO NOT MERGE

#757 rip out isLiveServer checks and corresponding tests
  README.md
  build/Jenkinsfile
  src/actions/admin.test.js
  src/actions/channels.test.js
  src/actions/files.test.js
  src/actions/jobs.test.js
  src/actions/posts.test.js
  src/actions/users.test.js
  src/actions/websocket.test.js
  test/actions/groups.test.js
  test/test_helper.js
Labels: 2: Dev Review

#755 Migrate to flow selectors and utils for posts
  .flowconfig
  src/selectors/entities/posts.js
  src/selectors/entities/posts.test.js
  src/store/initial_state.js
  src/types/posts.js
  src/types/search.js
  src/types/users.js
  src/utils/post_utils.js
Labels: 2: Dev Review

#758 add timeout for jenkins job
  build/Jenkinsfile
Labels: 3: Ready to Merge

#753 [MM-10346] CSRF Token Implementation
  src/client/client4.js
Labels: 2: Dev Review
