Repository mattermost/mattermost-redux, pull requests merged in 2019-02, with the labels that each got.

#759 Migrate to flow selectors of users
  .flowconfig
  package.json
  src/selectors/entities/users.js
  src/types/users.js
  src/types/utilities.js
  src/utils/user_utils.js
Labels: 2: Dev Review

#760 Store expanded URLs
  src/actions/general.js
  src/reducers/entities/posts.js
  src/reducers/entities/posts.test.js
  src/selectors/entities/posts.js
  src/selectors/entities/posts.test.js
  src/store/initial_state.js
  src/types/posts.js
Labels: Hackfest

#766 Dependencies Audit fix
  package-lock.json
Labels: 2: Dev Review

#735 MM-13188 Fix for channels with unreads having loading indicator placed above unread messages line
  src/actions/posts.test.js
  src/actions/websocket.js
  src/actions/websocket.test.js
  src/reducers/entities/posts.js
  src/reducers/entities/posts.test.js
Labels: 3: Ready to Merge

#762 MM-13956 Separate post reducers
  src/actions/posts.js
  src/reducers/entities/posts.js
  src/reducers/entities/posts.test.js
Labels: 3: Ready to Merge

#773 MM-13940: Replying then switching teams results in incorrect unread dot in team sidebar
  src/reducers/entities/teams.js
Labels: 3: Ready to Merge, CherryPickApproved

#774 MM-14115 Do not clobber reactions when dispatching RECEIVED_POST that has no reactions metadata
  src/reducers/entities/posts.js
  src/reducers/entities/posts.test.js
Labels: 3: Ready to Merge, CherryPickApproved

#763 Match webapp websocket actions
  src/actions/channels.js
  src/actions/posts.js
  src/actions/websocket.js
  src/constants/general.js
  src/utils/post_utils.js
Labels: 3: Ready to Merge, CherryPickApproved

#768 Fixed incorrect action dispatching +tests
  src/actions/general.js
  src/actions/general.test.js
  src/reducers/entities/posts.js
  src/reducers/entities/posts.test.js
Labels: Hackfest

#769 Added doPostActionWithCookie for MM-10516, actions in ephemeral messages
  src/actions/posts.js
  src/actions/posts.test.js
  src/client/client4.js
Labels: 2: Dev Review

#764 [MM-8421] Fix tiff preview - redux
  src/constants/files.js
Labels: 2: Dev Review, Hackfest

#767 MM-13957 Reorganize post actions
  src/action_types/posts.js
  src/actions/posts.js
  src/actions/posts.test.js
  src/actions/search.js
  src/actions/websocket.js
  src/actions/websocket.test.js
  src/reducers/entities/files.js
  src/reducers/entities/posts.js
  src/reducers/entities/posts.test.js
  src/reducers/entities/search.js
  src/reducers/entities/search.test.js
  src/selectors/entities/posts.js
  src/selectors/entities/posts.test.js
  src/store/initial_state.js
  src/types/posts.js
Labels: 3: Ready to Merge

#780 Handle pending posts when dispatching RECEIVED_NEW_POST
  src/reducers/entities/posts.js
  src/reducers/entities/posts.test.js
Labels: CherryPickApproved
