Repository mattermost/mattermost-redux, pull requests merged in 2019-09, with the labels that each got.

#915 [MM-17975] Some Pre-Packaged plugins show as removable in the UI
  src/constants/plugins.js
Labels: 2: Dev Review

#912 MM-17152 - Added support for plugins marketplace endpoint
  src/action_types/index.js
  src/action_types/plugins.js
  src/actions/plugins.js
  src/actions/plugins.test.js
  src/client/client4.js
  src/reducers/entities/index.js
  src/reducers/entities/plugins.js
  src/selectors/entities/plugins.js
  test/test_helper.js
Labels: 3: Reviews Complete

#906 [MM-14521] Added access to the new endpoint to test Site URLs
  src/action_types/admin.js
  src/actions/admin.js
  src/actions/admin.test.js
  src/client/client4.js
  src/reducers/requests/admin.js
  src/store/initial_state.js
  src/types/requests.js
Labels: 3: Reviews Complete

#919 [MM-18182] Don't show multiples of the same posts in pinned results
  src/reducers/entities/search.js
  src/reducers/entities/search.test.js
Labels: 3: Reviews Complete

#920 MM-17550 Added support for search term in get marketplace plugins
  src/actions/plugins.js
  src/actions/plugins.test.js
  src/client/client4.js
  src/reducers/entities/plugins.js
Labels: 2: QA Review

#922 MM-18103 - Added telemetry events for plugin marketplace
  src/client/client4.js
Labels: 3: Reviews Complete

#916 MM-14274: Check radio type dialog element for error
  src/utils/integration_utils.js
  src/utils/integration_utils.test.js
Labels: 3: Reviews Complete

#914 [MM-16934] Add support for update channel privacy API call
  src/actions/channels.js
  src/actions/channels.test.js
  src/client/client4.js
Labels: 3: Reviews Complete

#911 MM-17468 - Improving performance of fetching threads
  package-lock.json
  src/actions/posts.js
  src/client/client4.js
Labels: 3: Reviews Complete

#924 MM-17023: Plugin Marketplace
  src/action_types/index.js
  src/action_types/plugins.js
  src/actions/plugins.js
  src/actions/plugins.test.js
  src/client/client4.js
  src/reducers/entities/index.js
  src/reducers/entities/plugins.js
  src/selectors/entities/plugins.js
  test/test_helper.js
Labels: 2: QA Review, CherryPick/Approved

#927 Automated cherry pick of #924
  src/action_types/index.js
  src/action_types/plugins.js
  src/actions/plugins.js
  src/actions/plugins.test.js
  src/client/client4.js
  src/reducers/entities/index.js
  src/reducers/entities/plugins.js
  src/selectors/entities/plugins.js
  test/test_helper.js
Labels: AutomatedCherryPick

#925 MM-18512 Add support for options in get profiles in and without team
  src/actions/users.js
  src/client/client4.js
Labels: 3: Reviews Complete

#928 MM-17468 - Fix regression. Maintain reply_count on parent post when comments are created/deleted
  src/actions/posts.test.js
  src/reducers/entities/posts.js
Labels: 2: Dev Review, CherryPick/Approved

#929 Automated cherry pick of #928
  src/actions/posts.test.js
  src/reducers/entities/posts.js
Labels: AutomatedCherryPick

#918 [MM-17068] add websocket support for mark as unread
  src/actions/posts.js
  src/actions/websocket.js
  src/actions/websocket.test.js
  src/constants/websocket.js
  src/reducers/entities/teams.js
  src/selectors/entities/channels.js
Labels: 3: Reviews Complete

#931 MM-16399 Clear current channel when leaving a team
  src/actions/teams.js
  src/actions/teams.test.js
Labels: 3: Reviews Complete, CherryPick/Approved

#932 Automated cherry pick of #931
  src/actions/teams.js
  src/actions/teams.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#933 MM-18623 - Handle reply-count in getPostThread code path
  src/actions/posts.js
  src/actions/posts.test.js
  src/client/client4.js
Labels: 3: Reviews Complete, CherryPick/Approved

#934 Automated cherry pick of #933
  src/actions/posts.js
  src/actions/posts.test.js
  src/client/client4.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#935 MM-18624: revert fetch threads support
  package-lock.json
  src/actions/posts.js
  src/actions/posts.test.js
  src/client/client4.js
Labels: QA Review Done
