Repository mattermost/mattermost-redux, pull requests merged in 2019-10, with the labels that each got.

#930 [MM-17624] Update message count and unread count in redux on createPost
  src/actions/posts.js
Labels: 3: Reviews Complete, CherryPick/Approved

#937 Automated cherry pick of #930
  src/actions/posts.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#938 MM-18796 - Add POST `/plugins/marketplace` API to redux
  src/actions/plugins.js
  src/actions/plugins.test.js
  src/client/client4.js
Labels: 3: Reviews Complete

#941 [MM-19317] Fix nock url for delete preferences
  src/actions/preferences.test.js
Labels: 3: Reviews Complete, Hacktoberfest, QA Review Done, Tests/Not Needed

#943 MM-19318 - Update tracking events when marketplace plugin is installed
  src/client/client4.js
Labels: 2: Dev Review

#944 MM-19481 Stop reading marked channel when switching to a different channel
  src/actions/channels.js
  src/actions/channels.test.js
  src/selectors/entities/channels.js
  src/selectors/entities/channels.test.js
  src/utils/channel_utils.js
  src/utils/channel_utils.test.js
Labels: 3: Reviews Complete

#946 MM-19507 - Reactions on Deleted Messages
  src/reducers/entities/posts.test.js
  src/reducers/entities/posts.ts
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done, Tests/Not Needed

#948 Typescript build fix
  Makefile
  babel.config.js
  jest.config.js
Labels: 3: Reviews Complete

#949 Automated cherry pick of #946
  src/reducers/entities/posts.js
  src/reducers/entities/posts.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#952 Remove unused status flags in requests/general.js + typescript #12523
  src/action_types/general.ts
  src/actions/general.test.js
  src/actions/general.ts
  src/reducers/requests/general.ts
  src/store/initial_state.ts
  src/types/requests.ts
Labels: 3: Reviews Complete, Hacktoberfest, QA Review Done, Tests/Not Needed

#951 Adding new action type REMOVE_MEMBER_FROM_CHANNEL
  src/action_types/channels.ts
  src/reducers/entities/channels.test.js
  src/reducers/entities/channels.ts
Labels: 2: Dev Review, CherryPick/Approved, QA Review Done

#954 Automated cherry pick of #951
  src/action_types/channels.js
  src/reducers/entities/channels.js
  src/reducers/entities/channels.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#955 Remove unnecesary exports from reducers
  src/reducers/entities/channels.test.js
  src/reducers/entities/channels.ts
Labels: 3: Reviews Complete, QA Review Done

#956 MM-19448 Get user preferences on WebSocket reconnect
  src/actions/websocket.test.js
  src/actions/websocket.ts
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#958 Revert Cherry Pick of #956
  src/actions/websocket.js
  src/actions/websocket.test.js
Labels: 2: Dev Review

#961 Fixing mattermost redux build for the webapp
  .npmignore
  package.json
  src/actions/bots.ts
  src/actions/files.ts
  src/actions/integrations.ts
  src/actions/plugins.ts
  src/actions/websocket.ts
  src/reducers/entities/emojis.ts
  src/reducers/requests/groups.ts
  src/selectors/entities/files.ts
  src/selectors/entities/groups.ts
  src/selectors/entities/integrations.ts
  src/selectors/entities/plugins.ts
  src/selectors/entities/posts.ts
  src/selectors/entities/preferences.ts
  src/selectors/entities/roles.ts
  src/selectors/entities/roles_helpers.ts
  src/selectors/entities/search.ts
  src/selectors/entities/teams.ts
  src/store/configureStore.dev.ts
  src/store/configureStore.prod.ts
  src/store/middleware.ts
  src/utils/helpers.ts
  src/utils/post_list.ts
Labels: 3: Reviews Complete, QA Review Done, Tests/Not Needed
