Repository mattermost/mattermost-redux, pull requests merged in 2019-11, with the labels that each got.

#962 move marketplace plugins to webapp redux
  src/actions/index.ts
  src/actions/plugins.test.js
  src/actions/plugins.ts
  src/reducers/entities/index.ts
  src/reducers/entities/plugins.ts
  src/selectors/entities/index.ts
  src/selectors/entities/plugins.ts
Labels: 2: QA Review

#969 Automated cherry pick of #965
  src/store/helpers.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#970 Removing implicit anys from team selectors and reducers
  src/reducers/entities/teams.ts
  src/selectors/entities/teams.ts
Labels: 3: Reviews Complete, QA Review Done, Tests/Not Needed

#966 Removing some implicit anys
  src/utils/post_list.ts
Labels: 3: Reviews Complete, QA Review Done, Tests/Not Needed

#968 MM-19482 Stop rendering New Messages line differently for manually unread channels
  src/utils/post_list.ts
Labels: 3: Reviews Complete

#971 Removing implicit anys from client4.ts
  src/actions/users.ts
  src/client/client4.ts
  src/client/fetch_etag.ts
  src/types/client4.ts
Labels: 3: Reviews Complete, QA Review Done, Tests/Not Needed

#980 Make form-data a regular dependency
  package-lock.json
  package.json
Labels: 2: Dev Review

#979 Treat .txt and .rtf files as "text", instead of as "code"
  src/constants/files.ts
  src/utils/file_utils.ts
Labels: 3: Reviews Complete

#963 MM-19337 Enable users to view archived channels
  src/actions/channels.test.js
  src/actions/channels.ts
  src/client/client4.ts
Labels: 3: Reviews Complete, QA Review Done

#985 MM-19961 Sync persisted channels with server channels on RECEIVED_CHANNELS
  src/actions/websocket.test.js
  src/actions/websocket.ts
  src/reducers/entities/channels.ts
Labels: 3: Reviews Complete

#988 Fix type of filePublicLink state
  src/reducers/entities/files.ts
Labels: 2: Dev Review

#973 [MM-19309] Name Display Lock
  src/constants/preferences.ts
  src/selectors/entities/users.test.js
  src/selectors/entities/users.ts
  src/types/config.ts
  src/utils/user_utils.test.js
  src/utils/user_utils.ts
Labels: 3: Reviews Complete, QA Review Done

#989 Fix sync persisted channels
  package-lock.json
  src/actions/channels.ts
  src/actions/websocket.test.js
  src/reducers/entities/channels.ts
Labels: 3: Reviews Complete

#987 MM-18517: Plugin Marketplace (Phase 2)
  src/actions/index.ts
  src/actions/plugins.test.js
  src/actions/plugins.ts
  src/reducers/entities/index.ts
  src/reducers/entities/plugins.ts
  src/selectors/entities/index.ts
  src/selectors/entities/plugins.ts
  src/store/initial_state.ts
  src/types/store.ts
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#972 MM-16368 - Plugin Signing
  src/client/client4.ts
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#945 MM-18356: Update for newly-added ability to paginate channel searches.
  src/actions/channels.test.js
  src/actions/channels.ts
  src/client/client4.ts
Labels: 3: Reviews Complete, QA Review Done

#991 Adding AsymmetricSigningPublicKey to Config type
  src/types/config.ts
Labels: 3: Reviews Complete

#990 MM-20272 Prevent channel reducers from deleting the active channel.
  src/actions/channels.ts
  src/reducers/entities/channels.test.js
  src/reducers/entities/channels.ts
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done, Tests/Not Needed

#953 MM-18357: Adds ability to retrieve team search results paginated.
  src/actions/teams.test.js
  src/actions/teams.ts
  src/client/client4.ts
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#994 [MM-20725] Revert threads performance change on 5.18
  package-lock.json
  src/actions/posts.test.js
  src/actions/posts.ts
  src/client/client4.ts
  src/reducers/entities/posts.ts
Labels: 3: Reviews Complete, QA Review Done, Tests/Not Needed
