Repository mattermost/mattermost-redux, pull requests merged in 2019-08, with the labels that each got.

#891 MM-17385 If recent chunk is empty then return it for getUnreadPosts selector
  src/selectors/entities/posts.js
  src/selectors/entities/posts.test.js
Labels: 3: Reviews Complete, CherryPick/Approved

#892 Automated cherry pick of #891
  src/selectors/entities/posts.js
  src/selectors/entities/posts.test.js
Labels: AutomatedCherryPick/Done

#893 [MM-17200] Adds constants for new system posts for guests
  src/constants/posts.js
Labels: 2: Dev Review

#898 [MM-17390] Rate limited posts fail to load threads
  src/actions/posts.js
  src/actions/posts.test.js
Labels: 3: Reviews Complete

#900 [MM-17198] Send serverVersion to redux store on login and loadMe
  src/actions/users.js
  src/actions/users.test.js
  test/test_helper.js
Labels: 3: Reviews Complete

#902 MM-17917 Do not merge client license in reducer
  src/reducers/entities/general.js
Labels: 2: Dev Review

#901 MM-17866 Fix for channel loader when removing the last post in channel
  src/reducers/entities/posts.js
  src/reducers/entities/posts.test.js
Labels: 3: Reviews Complete, CherryPick/Approved

#905 Automated cherry pick of #901
  src/reducers/entities/posts.js
  src/reducers/entities/posts.test.js
Labels: AutomatedCherryPick/Done

#908 MM-17869 Making a post in empty channel sometimes shows just loader
  src/actions/posts.js
  src/actions/posts.test.js
  src/reducers/entities/posts.js
  src/reducers/entities/posts.test.js
  src/selectors/entities/posts.js
  src/selectors/entities/posts.test.js
  src/types/posts.js
Labels: 3: Reviews Complete, CherryPick/Approved

#910 Automated cherry pick of #908
  src/actions/posts.js
  src/actions/posts.test.js
  src/reducers/entities/posts.js
  src/reducers/entities/posts.test.js
  src/selectors/entities/posts.js
  src/selectors/entities/posts.test.js
  src/types/posts.js
Labels: AutomatedCherryPick/Done

#904 MM-17643 Add the ability of keeping an oldest flag for posts chunks
  src/actions/posts.js
  src/actions/posts.test.js
Labels: 3: Reviews Complete, CherryPick/Approved

#913 Automated cherry pick of #904
  src/actions/posts.js
  src/actions/posts.test.js
Labels: AutomatedCherryPick/Done
