Repository mattermost/mattermost-redux, pull requests merged in 2019-06, with the labels that each got.

#841 MM-15751 Fix for system messages not rendering in IE
  src/utils/post_list.js
Labels: 3: Reviews Complete, CherryPick/Approved

#844 #10883 Allow plugins to dismiss posts through the MessageWillBePosted hook
  src/actions/posts.js
Labels: 2: Dev Review

#848 [MM-16143] update prepackaged plugins list for 5.12
  src/constants/plugins.js
Labels: 3: Reviews Complete, CherryPick/Candidate

#851 MM-16280 when create post fails set the update_at field
  src/actions/posts.js
Labels: 2: Dev Review, CherryPick/Approved

#847 [MM-14727] Added a new post type constant to support the addition of a bot to …
  src/constants/posts.js
Labels: 2: Dev Review

#854 Fix channel sorting when display name is not set
  src/utils/channel_utils.js
  src/utils/channel_utils.test.js
Labels: 3: Reviews Complete, CherryPick/Approved

#850 MM-2954: Add a separate post type for /me messages and update formatting
  src/constants/posts.js
  src/utils/post_utils.js
  src/utils/post_utils.test.js
Labels: 2: Dev Review

#853 MM-16258: Add client and action for new API endpoint.
  src/action_types/teams.js
  src/actions/teams.js
  src/actions/teams.test.js
  src/client/client4.js
Labels: 3: Reviews Complete

#855 Set post list date separators based on the user timezone if available
  package-lock.json
  package.json
  src/selectors/entities/timezone.js
  src/utils/post_list.js
Labels: 3: Reviews Complete, CherryPick/Approved

#856 MM-16224: Add client and action for new API endpoint.
  src/action_types/channels.js
  src/actions/channels.js
  src/actions/channels.test.js
  src/client/client4.js
Labels: 2: Dev Review

#857 MM-16423 Fix missing posts when using since API
  src/reducers/entities/posts.js
  src/reducers/entities/posts.test.js
Labels: 3: Reviews Complete, CherryPick/Approved

#846 [MM-15942] Adds suggestions prefixed by split string
  src/utils/user_utils.js
  src/utils/user_utils.test.js
Labels: 3: Reviews Complete, CherryPick/Approved

#828 [MM-13500] Add search group channels method to client
  src/actions/channels.js
  src/actions/users.js
  src/client/client4.js
  src/constants/general.js
Labels: 3: Reviews Complete

#860 MM-16530: Adds group objects to state when requesting groups associat…
  src/actions/groups.test.js
  src/reducers/entities/groups.js
Labels: 3: Reviews Complete

#858 MM-16504: Adds total count of groups associated to teams and channels.
  src/actions/groups.test.js
  src/reducers/entities/channels.js
  src/reducers/entities/teams.js
  src/selectors/entities/groups.js
  src/selectors/entities/groups.test.js
Labels: 3: Reviews Complete

#862 MM-16480 Don't store incomplete channels
  src/actions/channels.test.js
  src/reducers/entities/channels.js
  src/reducers/entities/channels.test.js
  src/selectors/entities/channels.js
  src/selectors/entities/channels.test.js
Labels: 3: Reviews Complete, CherryPick/Approved

#859 MM-16500: Adds total team count to state.
  src/action_types/teams.js
  src/actions/teams.js
  src/actions/teams.test.js
  src/client/client4.js
  src/reducers/entities/teams.js
  src/store/initial_state.js
  src/types/teams.js
Labels: 3: Reviews Complete, Do Not Merge/Awaiting PR

#863 MM-16499: Adds ability to retrieve channels with the total count, sto…
  src/action_types/channels.js
  src/actions/channels.js
  src/actions/channels.test.js
  src/client/client4.js
  src/reducers/entities/channels.js
  src/store/initial_state.js
  src/types/channels.js
Labels: 2: Dev Review

#867 Add a link to the JS driver in PR template
  PULL_REQUEST_TEMPLATE.md
Labels: 3: Reviews Complete

#865 Adding promote/demote actions to redux
  src/actions/users.js
  src/client/client4.js
Labels: 3: Reviews Complete

#869 Adds optional chaining.
  babel.config.js
  package-lock.json
  package.json
  src/selectors/entities/groups.js
Labels: 3: Reviews Complete
