Repository mattermost/mattermost-redux, pull requests merged in 2019-07, with the labels that each got.

#870 MM-16477 Check for modified users on reconnect
  src/actions/users.js
  src/actions/users.test.js
  src/actions/websocket.js
  src/actions/websocket.test.js
  src/client/client4.js
  src/reducers/index.js
  src/reducers/websocket.js
  src/reducers/websocket.test.js
  src/store/initial_state.js
  src/types/store.js
Labels: 3: Reviews Complete

#868 [MM-14720] Add bot post counts per day
  src/actions/admin.js
  src/constants/stats.js
  src/reducers/entities/admin.js
  src/reducers/entities/admin.test.js
Labels: 3: Reviews Complete

#871 [MM-16376] Add installPluginFromUrl to Client and Actions
  src/action_types/admin.js
  src/actions/admin.js
  src/actions/admin.test.js
  src/client/client4.js
  src/reducers/requests/admin.js
  src/store/initial_state.js
  src/types/requests.js
Labels: 2: Dev Review

#872 Update NOTICE.txt
  NOTICE.txt
Labels: 3: Reviews Complete, CherryPick/Approved

#874 MM-16695 Add null check when deleting channel from postsInThread
  src/reducers/entities/posts.js
  src/reducers/entities/posts.test.js
Labels: 3: Reviews Complete, CherryPick/Approved

#864 MM-15783 Adding automatic CSRF from cookie
  src/client/client4.js
Labels: 3: Reviews Complete

#876 [MM-16389] Add client function to transform url to absolute
  src/client/client4.js
Labels: 3: Reviews Complete

#873 MM-11504: Add unread API actions and selectors for bi-directional scrolling
  src/actions/posts.js
  src/actions/posts.test.js
  src/client/client4.js
  src/reducers/entities/posts.js
  src/reducers/entities/posts.test.js
  src/selectors/entities/posts.js
  src/selectors/entities/posts.test.js
Labels: 3: Reviews Complete

#875 MM-11039
  src/actions/channels.js
  src/actions/users.js
  src/actions/websocket.js
  src/actions/websocket.test.js
  src/reducers/entities/search.test.js
  src/types/actions.js
Labels: 2: Dev Review

#880 MM-16829 Fix for websocket reconencts for android
  src/client/websocket_client.js
Labels: 3: Reviews Complete, CherryPick/Approved

#882 Guest accounts feature
  src/actions/teams.js
  src/actions/users.js
  src/client/client4.js
  src/constants/general.js
  src/constants/permissions.js
  src/selectors/entities/channels.js
Labels: 3: Reviews Complete, CherryPick/Approved

#884 Automated cherry pick of #882
  src/actions/teams.js
  src/actions/users.js
  src/client/client4.js
  src/constants/general.js
  src/constants/permissions.js
  src/selectors/entities/channels.js
Labels: AutomatedCherryPick/Done

#878 MM-16922 Opening a permalink from last few messages of a channel has a loading indicator at the bottom
  src/actions/posts.js
  src/actions/posts.test.js
Labels: 3: Reviews Complete, CherryPick/Approved

#883 MM-16915 Updating Dependencies
  babel.config.js
  package-lock.json
  package.json
  src/actions/emojis.js
  src/actions/emojis.test.js
  src/actions/posts.test.js
  src/actions/teams.test.js
  src/actions/users.test.js
  src/store/configureStore.dev.js
Labels: 2: Dev Review

#885 Automated cherry pick of #878
  src/actions/posts.js
  src/actions/posts.test.js
Labels: AutomatedCherryPick/Done

#888 [MM-14697] Filter archived teams out of team membership selectors
  src/selectors/entities/channels.test.js
  src/selectors/entities/teams.js
  src/selectors/entities/teams.test.js
Labels: 3: Reviews Complete, CherryPick/Approved

#889 Automated cherry pick of #887
  src/selectors/entities/channels.js
  src/selectors/entities/channels.test.js
Labels: AutomatedCherryPick/Done

#890 Automated cherry pick of #888
  src/selectors/entities/channels.test.js
  src/selectors/entities/teams.js
  src/selectors/entities/teams.test.js
Labels: AutomatedCherryPick/Done
