Repository mattermost/mattermost-redux, pull requests merged in 2019-12, with the labels that each got.

#998 [MM-20164] Dispatch redux when users role is changed from member to system admin or vice versa
  src/actions/websocket.ts
  src/constants/websocket.ts
Labels: QA Review Done

#999 Automated cherry pick of #998
  src/actions/websocket.ts
  src/constants/websocket.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#996 Update PULL_REQUEST_TEMPLATE.md
  PULL_REQUEST_TEMPLATE.md
Labels: 3: Reviews Complete

#975 MM-15719 Adding a util func getEmbedFromMetadata
  src/utils/post_utils.test.js
  src/utils/post_utils.ts
Labels: 3: Reviews Complete, QA Review Done

#1000 Update PULL_REQUEST_TEMPLATE.md
  PULL_REQUEST_TEMPLATE.md
Labels: 3: Reviews Complete

#997 MM-20260 - Email notification still sent while disabled in UI
  src/utils/notify_props.test.js
  src/utils/notify_props.ts
Labels: 3: Reviews Complete, QA Review Done

#1010 MM-20977 - Inviting multiple users with valid/allowed and invalid emails causes the invites for the valid users not to be sent
  src/actions/teams.ts
  src/client/client4.ts
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#1005 MM-20743 - CI uses npm ci instead of npm install
  .circleci/config.yml
Labels: 3: Reviews Complete, Tests/Not Needed

#995 [GH-10200] Isolate unit tests for channels selectors and make them more thorough
  src/selectors/entities/channels.test.js
Labels: 3: Reviews Complete, QA Review Done

#1011 Enable skipped tests and fix memoization of createIdsSelector
  src/utils/helpers.ts
  src/utils/post_list.test.js
Labels: 3: Reviews Complete, QA Review Done

#1013 MM-21153 Count mentions in DM channels using mention_count
  src/selectors/entities/channels.test.js
  src/selectors/entities/channels.ts
  test/test_helper.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#1014 Automated cherry pick of #1013
  src/selectors/entities/channels.test.js
  src/selectors/entities/channels.ts
  test/test_helper.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1015 Dismiss handlePostUnread WebSocket action is marked as unread locally
  src/action_types/channels.ts
  src/actions/posts.test.js
  src/actions/posts.ts
  src/actions/websocket.test.js
  src/actions/websocket.ts
  src/reducers/entities/channels.ts
Labels: 3: Reviews Complete, CherryPick/Approved

#981 Fix dependencies for react native app #978
  package-lock.json
  package.json
Labels: 3: Reviews Complete, QA Review Done

#1017 Automated cherry pick of #1016
  src/actions/users.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#992 MM 13527: Removal of unused status flags in Groups requests state object #13030
  src/action_types/groups.ts
  src/actions/groups.test.js
  src/actions/groups.ts
  src/reducers/requests/groups.ts
  src/reducers/requests/index.ts
  src/store/initial_state.ts
  src/types/requests.ts
  src/types/store.ts
Labels: 3: Reviews Complete, QA Review Done

#1019 Automated cherry pick of #997
  src/utils/notify_props.test.js
  src/utils/notify_props.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#964 MM-14622 Store OpenGraph data against a post id
  src/reducers/entities/posts.test.js
  src/reducers/entities/posts.ts
  src/selectors/entities/posts.ts
Labels: 3: Reviews Complete

#1001 [MM-10858] Update websocket actions
  src/actions/websocket.test.js
  src/actions/websocket.ts
Labels: 3: Reviews Complete, QA Review Done

#1008 MM-19614 - Added local_only parameter to GetMarketplacePlugins
  src/client/client4.ts
Labels: 3: Reviews Complete

#1021 MM-21262 - Removed prepackaged plugin flags
  src/constants/plugins.ts
  src/reducers/entities/admin.test.js
  src/reducers/entities/admin.ts
Labels: 3: Reviews Complete

#1024 MM-21290: Checks for license AND config prior to overriding user's di…
  src/selectors/entities/users.test.js
  src/selectors/entities/users.ts
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#1028 Automated cherry pick of #1024
  src/selectors/entities/users.test.js
  src/selectors/entities/users.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed
