Repository mattermost/mattermost-redux, pull requests merged in 2019-03, with the labels that each got.

#785 [MM-14315] Fix undefined site URL when copying permalink
  src/selectors/entities/teams.js
  src/selectors/entities/teams.test.js
Labels: 3: Ready to Merge, CherryPickApproved

#783 [MM-13863] Fix unnecessary sorting of channels recency on reaction to a post
  src/utils/channel_utils.js
  src/utils/channel_utils.test.js
Labels: 2: Dev Review

#765 Splitting emojis and webhooks permissions
  src/constants/permissions.js
Labels: 3: Ready to Merge

#787 Export isUnreadChannel from channel_utils
  src/utils/channel_utils.js
Labels: 3: Ready to Merge

#786 Properly handle newly received posts
  src/actions/posts.js
Labels: 3: Ready to Merge

#791 MM-1447: check post?.metadata?.files, not just metadata
  src/reducers/entities/files.js
  src/reducers/entities/files.test.js
Labels: 3: Ready to Merge, CherryPickApproved

#790 MM-14415: Removes 'can_leave' field.
  src/types/groups.js
  test/actions/groups.test.js
Labels: 3: Ready to Merge

#792 [MM-14527] Add INTERVAL_NOT_SET for email interval preference
  src/constants/preferences.js
Labels: 2: Dev Review, CherryPickApproved

#788 MM-12488: Adds new query params options when getting LDAP groups.
  src/actions/admin.js
  src/actions/admin.test.js
  src/client/client4.js
  src/types/groups.js
Labels: Awaiting PR

#789 MM-13960 Move preparePostIdsForPostList from mobile and re-add combined system posts
  src/actions/posts.js
  src/selectors/entities/posts.js
  src/utils/post_list.js
  src/utils/post_list.test.js
  src/utils/post_utils.js
  src/utils/post_utils.test.js
Labels: 3: Ready to Merge

#779 Added join/list public/private teams permissions
  src/actions/teams.js
  src/constants/permissions.js
  src/selectors/entities/general.js
  src/selectors/entities/teams.js
  src/selectors/entities/teams.test.js
  src/utils/team_utils.js
  test/test_helper.js
Labels: 3: Ready to Merge

#784 [Documentation] simplified the "Promise" example
  README.md
Labels: 3: Ready to Merge

#796 MM-13621 Fixing some bots actions.
  src/actions/bots.js
  src/actions/bots.test.js
  src/client/client4.js
Labels: 2: Dev Review

#797 Used user TOS data embedded in user object itself
  src/actions/users.js
  src/actions/users.test.js
  src/client/client4.js
  src/reducers/entities/users.js
  src/selectors/entities/users.js
  src/selectors/entities/users.test.js
  src/store/initial_state.js
  src/types/users.js
Labels: 3: Ready to Merge

#798 MM-14748: Allow to invalidate email invites
  src/actions/teams.js
  src/client/client4.js
Labels: 3: Ready to Merge, CherryPickApproved
