Repository mattermost/mattermost-redux, pull requests merged in 2020-05, with the labels that each got.

#1144 MM-24912/MM-24913/MM-24336 Add redux actions for re-ordering channels and categories
  src/actions/channel_categories.test.js
  src/actions/channel_categories.ts
  src/actions/channels.test.js
  src/actions/channels.ts
  src/constants/channel_categories.ts
  src/reducers/entities/channel_categories.test.js
  src/reducers/entities/channel_categories.ts
  src/selectors/entities/channel_categories.test.js
  src/selectors/entities/channel_categories.ts
  src/selectors/entities/channels.ts
  src/selectors/entities/preferences.ts
  src/types/channel_categories.ts
  tsconfig.json
Labels: 4: Reviews Complete

#1146 MM-24916 Add redux actions to create/rename custom categories
  src/actions/channel_categories.test.js
  src/actions/channel_categories.ts
  src/reducers/entities/channel_categories.ts
  src/selectors/entities/channel_categories.ts
  src/utils/array_utils.test.ts
  src/utils/array_utils.ts
Labels: 4: Reviews Complete

#1147 Remove debug code
  src/actions/channel_categories.ts
Labels: 2: Dev Review

#1148 MM-24967 - Fix new post analytics
  src/client/client4.ts
Labels: 4: Reviews Complete, CherryPick/Approved

#1135 MM-23816: Group Mentions: Add ability to rename group names
  src/actions/groups.test.js
  src/types/groups.ts
Labels: 4: Reviews Complete

#1152 [MM-24695] Only highlight groups you are apart of yellow
  src/action_types/groups.ts
  src/actions/groups.ts
  src/client/client4.ts
  src/reducers/entities/groups.ts
  src/selectors/entities/groups.test.js
  src/selectors/entities/groups.ts
  src/selectors/entities/search.test.js
  src/store/initial_state.ts
  src/types/groups.ts
Labels: 4: Reviews Complete

#1094 Adding call for purge bleve indexes
  src/client/client4.ts
Labels: 4: Reviews Complete

#1157 Fix lint error
  src/client/client4.ts
Labels: 4: Reviews Complete

#1113 MM-23395: Add websockets support for update group for group mentions
  src/action_types/groups.ts
  src/actions/channels.ts
  src/actions/websocket.test.js
  src/actions/websocket.ts
  src/constants/general.ts
  src/constants/websocket.ts
  src/reducers/entities/channels.ts
  src/reducers/entities/groups.ts
  src/reducers/entities/teams.ts
  test/test_helper.js
Labels: 4: Reviews Complete

#1156 MM-25126 Add separate Default sorting method
  src/actions/channel_categories.test.js
  src/actions/channel_categories.ts
  src/constants/channel_categories.ts
  src/reducers/entities/channel_categories.ts
  src/selectors/entities/channel_categories.test.js
  src/selectors/entities/channel_categories.ts
  src/types/channel_categories.ts
Labels: 4: Reviews Complete

#1150 [MM-14906] Add a new selector to getProfilesNotInTeam
  src/selectors/entities/users.test.js
  src/selectors/entities/users.ts
Labels: 4: Reviews Complete

#1162 Fully type Client4 methods
  src/actions/channels.ts
  src/actions/errors.ts
  src/actions/posts.ts
  src/actions/search.ts
  src/actions/teams.ts
  src/client/client4.ts
  src/client/fetch_etag.ts
  src/reducers/entities/admin.ts
  src/reducers/entities/general.ts
  src/reducers/entities/groups.ts
  src/selectors/entities/general.ts
  src/selectors/entities/teams.ts
  src/store/initial_state.ts
  src/types/admin.ts
  src/types/audits.ts
  src/types/autocomplete.ts
  src/types/channels.ts
  src/types/client4.ts
  src/types/compliance.ts
  src/types/config.ts
  src/types/errors.ts
  src/types/general.ts
  src/types/groups.ts
  src/types/integration_actions.ts
  src/types/integrations.ts
  src/types/message_attachments.ts
  src/types/mfa.ts
  src/types/plugins.ts
  src/types/posts.ts
  src/types/saml.ts
  src/types/sessions.ts
  src/types/teams.ts
  src/types/terms_of_service.ts
  src/types/users.ts
Labels: 4: Reviews Complete

#1158 MM-22155 ESLint configuration updates part 1
  .eslintrc.json
  src/actions/admin.test.js
  src/actions/channels.test.js
  src/actions/channels.ts
  src/actions/files.ts
  src/actions/general.ts
  src/actions/gifs.ts
  src/actions/groups.test.js
  src/actions/helpers.ts
  src/actions/posts.test.js
  src/actions/posts.ts
  src/actions/preferences.test.js
  src/actions/roles.ts
  src/actions/schemes.ts
  src/actions/teams.test.js
  src/actions/teams.ts
  src/actions/users.ts
  src/actions/websocket.test.js
  src/actions/websocket.ts
  src/client/fetch_etag.ts
  src/index.ts
  src/reducers/entities/admin.ts
  src/reducers/entities/channel_categories.test.js
  src/reducers/entities/channel_categories.ts
  src/reducers/entities/groups.ts
  src/reducers/entities/teams.ts
  src/selectors/entities/channel_categories.test.js
  src/selectors/entities/channel_categories.ts
  src/selectors/entities/channels.test.js
  src/selectors/entities/channels.ts
  src/selectors/entities/groups.ts
  src/selectors/entities/index.ts
  src/selectors/entities/posts.ts
  src/selectors/entities/preferences.ts
  src/selectors/entities/roles.ts
  src/selectors/index.ts
  src/store/configureStore.dev.ts
  src/utils/channel_utils.ts
  src/utils/index.ts
  src/utils/user_utils.test.js
Labels: 4: Reviews Complete

#1163 Update languages from 12 to 16
  README.md
Labels: 4: Reviews Complete, Tests/Not Needed
