Repository mattermost/mattermost-redux, pull requests merged in 2020-04, with the labels that each got.

#1119 Fix getChannelByNameAndTeamName.
  src/client/client4.ts
Labels: 3: Reviews Complete, CherryPick/Approved

#1120 Automated cherry pick of #1119
  src/client/client4.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1079 Adding support for thread optional fetching
  src/actions/posts.test.js
  src/actions/posts.ts
  src/client/client4.ts
  src/reducers/entities/posts.test.js
  src/reducers/entities/posts.ts
  src/selectors/entities/posts.ts
  src/store/initial_state.ts
  src/types/posts.ts
Labels: 3: Reviews Complete, QA Review Done

#1114 MM-23756 Always show unread DMs and GMs in new sidebar
  src/selectors/entities/channel_categories.test.js
  src/selectors/entities/channel_categories.ts
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#1122 Automated cherry pick of #1114
  src/selectors/entities/channel_categories.test.js
  src/selectors/entities/channel_categories.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1116 Update client4.ts: fix typo
  src/client/client4.ts
Labels: 3: Reviews Complete, QA Review Done

#1074 Update Dependencies
  package-lock.json
  package.json
  src/actions/channels.test.js
  src/actions/emojis.test.js
  src/actions/emojis.ts
  src/actions/general.test.js
  src/actions/general.ts
  src/actions/gifs.ts
  src/actions/posts.test.js
  src/actions/posts.ts
  src/actions/teams.test.js
  src/actions/teams.ts
  src/actions/users.test.js
  src/actions/users.ts
  src/actions/websocket.test.js
  src/client/client4.ts
  src/client/websocket_client.ts
  src/reducers/entities/channel_categories.test.js
  src/reducers/entities/typing.test.js
  src/reducers/requests/admin.ts
  src/reducers/requests/channels.ts
  src/reducers/requests/files.ts
  src/reducers/requests/general.ts
  src/reducers/requests/helpers.ts
  src/reducers/requests/jobs.ts
  src/reducers/requests/posts.ts
  src/reducers/requests/roles.ts
  src/reducers/requests/search.ts
  src/reducers/requests/teams.ts
  src/reducers/requests/users.ts
  src/selectors/entities/channel_categories.ts
  src/selectors/entities/channels.ts
  src/selectors/entities/emojis.ts
  src/selectors/entities/files.ts
  src/selectors/entities/general.ts
  src/selectors/entities/groups.ts
  src/selectors/entities/integrations.ts
  src/selectors/entities/jobs.ts
  src/selectors/entities/posts.ts
  src/selectors/entities/preferences.test.js
  src/selectors/entities/preferences.ts
  src/selectors/entities/roles.ts
  src/selectors/entities/search.ts
  src/selectors/entities/teams.ts
  src/selectors/entities/users.ts
  src/store/configureStore.dev.ts
  src/store/configureStore.prod.ts
  src/utils/channel_utils.ts
  src/utils/deep_freeze.ts
  src/utils/emoji_utils.test.js
  src/utils/post_list.ts
  src/utils/theme_utils.ts
Labels: QA Review Done

#1121 [MM-21494] Add support of the autocomplete suggestions
  src/client/client4.ts
Labels: 3: Reviews Complete

#1123 Remove nickname duplication on profile suggestion
  src/utils/user_utils.ts
Labels: QA Review Done

#1125 Fix missing trailing comma
  src/client/client4.ts
Labels: 3: Reviews Complete

#1106 fix fakeDmChannel to ensure correct user id order
  test/test_helper.js
Labels: 3: Reviews Complete

#1117 Clean up code style in selectors
  src/selectors/entities/alerts.ts
  src/selectors/entities/channels.test.js
  src/selectors/entities/channels.ts
  src/selectors/entities/common.ts
  src/selectors/entities/emojis.ts
  src/selectors/entities/files.ts
  src/selectors/entities/general.ts
  src/selectors/entities/groups.ts
  src/selectors/entities/i18n.ts
  src/selectors/entities/integrations.ts
  src/selectors/entities/jobs.ts
  src/selectors/entities/posts.ts
  src/selectors/entities/preferences.ts
  src/selectors/entities/roles.ts
  src/selectors/entities/roles_helpers.ts
  src/selectors/entities/schemes.ts
  src/selectors/entities/search.ts
  src/selectors/entities/teams.ts
  src/selectors/entities/typing.ts
  src/selectors/entities/users.ts
  src/types/preferences.ts
  src/utils/channel_utils.ts
Labels: 3: Reviews Complete

#1066 MM-23015: Enable or disable group mentions
  src/action_types/groups.ts
  src/actions/groups.test.js
  src/actions/groups.ts
  src/client/client4.ts
  src/reducers/entities/channels.ts
  src/reducers/entities/groups.ts
  src/reducers/entities/teams.ts
  src/selectors/entities/groups.test.js
  src/selectors/entities/groups.ts
  src/types/groups.ts
  src/utils/group_utils.test.ts
  src/utils/group_utils.ts
Labels: 2: Dev Review, QA Review Done

#1128 Fix exported type definitions for selectors
  src/selectors/entities/files.ts
  src/selectors/entities/groups.ts
  src/selectors/entities/integrations.ts
  src/selectors/entities/preferences.ts
  src/selectors/entities/roles.ts
  src/selectors/entities/roles_helpers.ts
  src/selectors/entities/search.ts
  src/selectors/entities/teams.ts
Labels: 3: Reviews Complete

#1129 Fix missing and incorrect types
  src/selectors/entities/teams.ts
  src/types/teams.ts
Labels: 3: Reviews Complete

#1127 [MM-23159] Highlight Group Names
  src/selectors/entities/groups.test.js
  src/selectors/entities/groups.ts
  src/selectors/entities/search.test.js
  src/selectors/entities/search.ts
Labels: 3: Reviews Complete, QA Review Done

#1115 MM-23251 Always show the current channel, even if it has been archived
  src/selectors/entities/channel_categories.test.js
  src/selectors/entities/channel_categories.ts
Labels: 3: Reviews Complete, CherryPick/Approved

#1130 MM-24306 Remove unused alerts code
  src/action_types/alerts.ts
  src/action_types/index.ts
  src/actions/alerts.test.js
  src/actions/alerts.ts
  src/actions/index.ts
  src/constants/alerts.ts
  src/constants/index.ts
  src/reducers/entities/alerts.ts
  src/reducers/entities/index.ts
  src/selectors/entities/alerts.test.js
  src/selectors/entities/alerts.ts
  src/selectors/entities/index.ts
  src/store/initial_state.ts
  src/types/alerts.ts
  src/types/index.ts
  src/types/store.ts
Labels: 3: Reviews Complete

#1105 MM-23569: Add rudder to diagnostics feature.
  src/client/client4.ts
Labels: 3: Reviews Complete, CherryPick/Approved

#1132 Automated cherry pick of #1105
  src/client/client4.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1133 Automated cherry pick of #1115
  src/selectors/entities/channel_categories.test.js
  src/selectors/entities/channel_categories.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1118 [MM-5881] Add support for searching by position in user lists
  src/utils/user_utils.ts
Labels: 3: Reviews Complete, QA Review Done

#1131 MM-23991 Add ability to sort DM channels in the new sidebar
  src/actions/channel_categories.test.js
  src/actions/channel_categories.ts
  src/constants/channel_categories.ts
  src/reducers/entities/channel_categories.ts
  src/selectors/entities/channel_categories.test.js
  src/selectors/entities/channel_categories.ts
  src/types/channel_categories.ts
Labels: 3: Reviews Complete

#1086 [MM-23264] Get channel member counts by group
  src/action_types/channels.ts
  src/actions/channels.test.js
  src/actions/channels.ts
  src/client/client4.ts
  src/reducers/entities/channels.test.js
  src/reducers/entities/channels.ts
  src/selectors/entities/channels.test.js
  src/selectors/entities/channels.ts
  src/store/initial_state.ts
  src/types/channels.ts
Labels: 3: Reviews Complete, QA Review Done

#1139 MM-22471 - Implement Product Analytics to measure threads, posts and replies
  src/client/client4.ts
Labels: 3: Reviews Complete, AutomatedCherryPick, CherryPick/Approved, Docs/Needed, QA Review Done

#1141 Automated cherry pick of #1139
  src/client/client4.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1138 Fixing users cleanup on leave/remove guest from channel
  src/actions/users.ts
  src/actions/websocket.test.js
  src/actions/websocket.ts
  src/client/client4.ts
  src/reducers/entities/channels.ts
  src/selectors/entities/channels.test.js
  src/selectors/entities/channels.ts
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done
