Repository mattermost/mattermost-redux, pull requests merged in 2020-11, with the labels that each got.

#1272 [MM-20481] Add 'link' as a possible PostEmbedType
  src/types/posts.ts
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#1258 Locations
  src/action_types/apps.ts
  src/action_types/index.ts
  src/actions/apps.ts
  src/client/client4.ts
  src/constants/apps.ts
  src/reducers/entities/apps.ts
  src/reducers/entities/index.ts
  src/selectors/entities/apps.ts
  src/store/initial_state.ts
  src/types/apps.ts
  src/types/integrations.ts
  src/types/store.ts
Labels: 4: Reviews Complete

#1281 [MM-20581] Update method signature for getGroupsAssociatedToChannel
  src/actions/groups.ts
Labels: 4: Reviews Complete

#1282 MM-30090 Add ManagedResourcePaths setting
  src/selectors/entities/general.test.js
  src/selectors/entities/general.ts
  src/types/config.ts
Labels: 4: Reviews Complete, CherryPick/Approved

#1283 Automated cherry pick of #1282
  src/selectors/entities/general.test.js
  src/selectors/entities/general.ts
  src/types/config.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1284 [MM-20581] Change `Groups` constant to `enum`
  src/constants/groups.ts
Labels: 4: Reviews Complete

#1279 MM-19509 Prioritize autocomplete results based on interactions and threads
  src/selectors/entities/posts.test.js
  src/selectors/entities/posts.ts
  src/selectors/entities/utils.test.js
  src/selectors/entities/utils.ts
  src/types/users.ts
Labels: 4: Reviews Complete

#1269 [MM-27556] UI For new system roles
  src/constants/permissions.ts
  src/constants/permissions_sysconsole.ts
Labels: 4: Reviews Complete

#1292 Updates for app modals
  src/types/apps.ts
  src/types/integrations.ts
Labels: 4: Reviews Complete

#1291 Fix ChannelModeration to be consistent with ChannelModerationRoles
  src/types/channels.ts
Labels: 4: Reviews Complete

#1294 [MM-30317] add MANAGE_REMOTE_CLUSTERS permission
  src/constants/permissions.ts
Labels: 4: Reviews Complete

#1295 [MM-30158] Added method for moving multiple channels from any number of categories to one category.
  src/actions/channel_categories.test.js
  src/actions/channel_categories.ts
  src/utils/array_utils.test.ts
  src/utils/array_utils.ts
Labels: 4: Reviews Complete

#1286 MM-20897 Add category muting
  src/action_types/channels.ts
  src/actions/channel_categories.test.js
  src/actions/channel_categories.ts
  src/actions/channels.test.js
  src/actions/channels.ts
  src/constants/channels.ts
  src/constants/general.ts
  src/reducers/entities/channels.ts
  src/selectors/entities/channel_categories.test.js
  src/types/channel_categories.ts
  src/utils/channel_utils.ts
Labels: 4: Reviews Complete

#1287 Updated apps types to reflect server changes
  src/constants/apps.ts
  src/selectors/entities/apps.ts
  src/types/apps.ts
  src/types/integrations.ts
Labels: 2: Dev Review

#1298 [MM-20423]: Update type.
  src/types/posts.ts
Labels: 4: Reviews Complete, QA Review Done

#1297 Some fixes to sync with lev-clenaup branch on apps
  src/reducers/entities/apps.ts
  src/selectors/entities/apps.ts
  src/types/apps.ts
Labels: 2: Dev Review

#1293 MM-30087 Remove direct dependency between Client4 and Rudder
  src/client/client4.test.js
  src/client/client4.ts
  src/client/index.ts
  src/client/rudder.ts
  src/client/telemetry.ts
Labels: 4: Reviews Complete

#1300 [MM-27927] - Add user preference for limit on dms and gms
  src/constants/preferences.ts
  src/selectors/entities/channel_categories.test.js
  src/selectors/entities/channel_categories.ts
Labels: 4: Reviews Complete

#1302 Allow description field of form field to be optional
  src/types/apps.ts
Labels: 4: Reviews Complete

#1303 Updates for App Commands
  src/client/client4.ts
  src/constants/apps.ts
  src/reducers/entities/apps.ts
  src/selectors/entities/apps.ts
  src/types/apps.ts
  src/types/integrations.ts
Labels: 4: Reviews Complete

#1304 [MM-20400] Add IsDefaultMarketplace to ClientConfig
  src/types/config.ts
  src/types/plugins.ts
Labels: 2: Dev Review
