Repository mattermost/mattermost-redux, pull requests merged in 2020-08, with the labels that each got.

#1212 [MM-26972] Allow pagination props for getGroups
  src/actions/groups.test.js
  src/actions/groups.ts
  src/client/client4.ts
Labels: 4: Reviews Complete, CherryPick/Approved

#1213 Automated cherry pick of #1212
  src/actions/groups.test.js
  src/actions/groups.ts
  src/client/client4.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1201 Add Selectors to get all the recent channel Ids
  src/selectors/entities/channels.test.js
  src/selectors/entities/channels.ts
Labels: 4: Reviews Complete

#1194 [MM-24300] Upgrade dependencies 5.28
  package-lock.json
  package.json
  src/client/client4.ts
  tsconfig.json
Labels: 4: Reviews Complete

#1215 Remove WebSocket actions
  src/actions/posts.test.js
  src/actions/posts.ts
  src/actions/websocket.test.js
  src/actions/websocket.ts
  src/types/websocket.ts
Labels: 4: Reviews Complete

#1218 MM-27930 - Cloud license feature
  src/types/config.ts
Labels: 4: Reviews Complete

#1216 MM-27635: Hide internal bots from UX
  src/selectors/entities/bots.test.ts
  src/selectors/entities/bots.ts
Labels: 2: Dev Review, 4: Reviews Complete, CherryPick/Approved

#1219 Automated cherry pick of #1216
  src/selectors/entities/bots.test.ts
  src/selectors/entities/bots.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1159 Fix new message indicator not showing for webhook messages to webhook owner
  src/utils/post_list.ts
Labels: 3: QA Review, 4: Reviews Complete

#1220 Admin Advisor: get metric status on refresh for admins only
  src/selectors/entities/users.ts
Labels: 4: Reviews Complete, CherryPick/Approved

#1223 Automated cherry pick of #1220
  src/selectors/entities/users.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1214 [MM-27132] Get mention keys associated to channel
  src/selectors/entities/groups.test.js
  src/selectors/entities/groups.ts
  src/selectors/entities/search.ts
Labels: 4: Reviews Complete, CherryPick/Approved

#1225 Automated cherry pick of #1214
  src/selectors/entities/groups.test.js
  src/selectors/entities/groups.ts
  src/selectors/entities/search.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1227 [MM-28200] Permission constants for new Billing and Account sections of Admin Console
  src/constants/permissions.ts
  src/constants/permissions_sysconsole.ts
Labels: 4: Reviews Complete
