Repository mattermost/mattermost-redux, pull requests merged in 2020-07, with the labels that each got.

#1182 [MM-26363] - Check if channel belong to category before dispatching addChannelToInitialCategory
  src/actions/channel_categories.ts
Labels: 4: Reviews Complete

#1179 Update NOTICE.txt
  NOTICE.txt
Labels: 4: Reviews Complete, CherryPick/Approved

#1185 Sidebar V2 Phase 2
  src/actions/channel_categories.test.js
  src/actions/channel_categories.ts
  src/actions/channels.test.js
  src/actions/channels.ts
  src/client/client4.ts
  src/constants/channel_categories.ts
  src/constants/preferences.ts
  src/reducers/entities/channel_categories.test.js
  src/reducers/entities/channel_categories.ts
  src/selectors/entities/channel_categories.test.js
  src/selectors/entities/channel_categories.ts
  src/selectors/entities/channels.ts
  src/selectors/entities/preferences.ts
  src/types/channel_categories.ts
  src/utils/array_utils.test.ts
  src/utils/array_utils.ts
  test/test_helper.js
  tsconfig.json
Labels: 4: Reviews Complete

#1186 MM-26685 Add a variable for client to disable sending events on rudder
  src/client/client4.test.js
  src/client/client4.ts
Labels: 4: Reviews Complete

#1190 [MM-26574] Add role filters to user search
  src/action_types/users.ts
  src/actions/users.ts
  src/client/client4.ts
  src/reducers/entities/users.test.js
  src/reducers/entities/users.ts
  src/selectors/entities/common.ts
  src/selectors/entities/users.test.js
  src/selectors/entities/users.ts
  src/types/users.ts
  src/utils/user_utils.test.js
  src/utils/user_utils.ts
Labels: 4: Reviews Complete

#1202 Automated cherry pick of #1197
  src/actions/channel_categories.test.js
  src/actions/channel_categories.ts
  src/actions/channels.test.js
  src/actions/channels.ts
  src/selectors/entities/channels.test.js
  src/selectors/entities/channels.ts
  src/selectors/entities/preferences.ts
  src/utils/channel_utils.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1187 [MM-26322] - Optimistically update the order of channels/categories when dragging
  src/actions/channel_categories.test.js
  src/actions/channel_categories.ts
Labels: 4: Reviews Complete, CherryPick/Approved

#1193 Added Helper function in channels to retrieve all direct channel name…
  src/selectors/entities/channels.ts
Labels: 4: Reviews Complete, CherryPick/Approved

#1203 Automated cherry pick of #1193
  src/selectors/entities/channels.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1199 MM-26801 Sort muted channels to the bottom when using alphabetical sorting
  src/selectors/entities/channel_categories.test.js
  src/selectors/entities/channel_categories.ts
Labels: 4: Reviews Complete, CherryPick/Approved

#1143 Add metric warning support (announcement bar and DM)
  src/action_types/general.ts
  src/actions/admin.test.js
  src/actions/admin.ts
  src/actions/general.test.js
  src/actions/general.ts
  src/actions/websocket.ts
  src/client/client4.ts
  src/constants/posts.ts
  src/constants/stats.ts
  src/constants/websocket.ts
  src/reducers/entities/admin.ts
  src/reducers/entities/general.ts
  src/selectors/entities/general.ts
  src/store/initial_state.ts
  src/types/config.ts
  src/types/general.ts
Labels: 4: Reviews Complete, CherryPick/Approved

#1192 [MM-26824] [MM-25990] Add channel filters to searchAllChannels
  src/actions/channels.test.js
  src/actions/channels.ts
  src/client/client4.ts
  src/types/channels.ts
Labels: 4: Reviews Complete, CherryPick/Approved

#1195 [MM-26219] Add option to include member count when getting all groups for team or channel
  src/actions/groups.test.js
  src/actions/groups.ts
  src/client/client4.ts
Labels: 4: Reviews Complete, CherryPick/Approved

#1191 [MM-19640] - Add download link for job results (Include new config setting)
  src/types/config.ts
Labels: 4: Reviews Complete

#1200 [MM-26969] Add filters options to team search
  src/actions/teams.test.js
  src/actions/teams.ts
  src/client/client4.ts
  src/types/teams.ts
Labels: 4: Reviews Complete

#1206 MM-26023 Move handling of sidebar API responses to the websocket
  src/actions/channel_categories.test.js
  src/actions/channel_categories.ts
Labels: 4: Reviews Complete, CherryPick/Approved

#1198 [MM-26958] function to sort channels by supplied channel type list
  src/utils/channel_utils.test.js
  src/utils/channel_utils.ts
Labels: 4: Reviews Complete

#1208 MM-26971 Fix GM duplicates when created and already exists in a category
  src/actions/channel_categories.test.js
  src/actions/channel_categories.ts
Labels: 4: Reviews Complete, CherryPick/Approved

#1209 [MM-27371] Include regenerate team invite id to update state
  src/actions/teams.test.js
  src/reducers/entities/teams.ts
Labels: 3: QA Review, CherryPick/Approved

#1210 Automated cherry pick of #1209
  src/actions/teams.test.js
  src/reducers/entities/teams.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1205 Update NOTICE.txt
  NOTICE.txt
Labels: 4: Reviews Complete, CherryPick/Approved

#1211 Automated cherry pick of #1205
  NOTICE.txt
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed
