Repository mattermost/mattermost-redux, pull requests merged in 2020-02, with the labels that each got.

#1045 Update dependencies.
  Makefile
  package-lock.json
  package.json
  src/actions/bots.test.js
  src/actions/channels.test.js
  src/actions/emojis.test.js
  src/actions/files.test.js
  src/actions/integrations.test.js
  src/actions/posts.test.js
  src/actions/preferences.test.js
  src/actions/schemes.test.js
  src/actions/search.test.js
  src/actions/teams.test.js
  src/actions/users.test.js
  src/actions/websocket.test.js
  test/test_helper.js
Labels: 3: Reviews Complete, QA Review Done

#1047 Missing is_bot and last_picture_update from UserProfile type
  src/types/users.ts
Labels: 3: Reviews Complete

#1046 [MM-21919] Add channel mentions permission to list of permissions
  src/constants/permissions.ts
Labels: 2: Dev Review

#1026 MM-18900 - Remove unused status flags in Search request state object
  src/action_types/search.ts
  src/actions/search.ts
  src/reducers/entities/search.ts
  src/reducers/requests/index.ts
  src/reducers/requests/search.ts
  src/store/initial_state.ts
  src/types/requests.ts
  src/types/store.ts
Labels: 3: Reviews Complete, QA Review Done

#1050 Re-enable ESLint for test files
  package.json
  src/actions/admin.test.js
  src/actions/channels.test.js
  src/selectors/entities/users.test.js
  src/utils/user_utils.test.js
Labels: 3: Reviews Complete

#1048 [MM-22205] [MM-22206] Add GetChannelModerations and PatchChannelModerations
  src/action_types/channels.ts
  src/actions/channels.test.js
  src/actions/channels.ts
  src/client/client4.ts
  src/constants/permissions.ts
  src/reducers/entities/channels.test.js
  src/reducers/entities/channels.ts
  src/selectors/entities/channels.test.js
  src/selectors/entities/channels.ts
  src/store/initial_state.ts
  src/types/channels.ts
  src/types/schemes.ts
Labels: 2: Dev Review

#1049 Performance improvements for mobile app
  src/action_types/channels.ts
  src/action_types/general.ts
  src/action_types/users.ts
  src/actions/roles.ts
  src/reducers/entities/channels.ts
  src/reducers/entities/general.ts
  src/reducers/entities/preferences.ts
  src/reducers/entities/teams.ts
  src/reducers/entities/users.ts
  src/types/teams.ts
  src/utils/post_list.test.js
  src/utils/post_list.ts
Labels: 3: Reviews Complete, CherryPick/Approved

#1054 Automated cherry pick of #1049
  src/action_types/channels.ts
  src/action_types/general.ts
  src/action_types/users.ts
  src/actions/roles.ts
  src/reducers/entities/channels.ts
  src/reducers/entities/general.ts
  src/reducers/entities/preferences.ts
  src/reducers/entities/teams.ts
  src/reducers/entities/users.ts
  src/types/teams.ts
  src/utils/post_list.test.js
  src/utils/post_list.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1053 Add ClientPluginManifest type
  src/types/plugins.ts
Labels: 3: Reviews Complete

#1051 Synchronize archived channels with storage
  src/actions/channels.test.js
  src/actions/channels.ts
  src/client/client4.ts
  src/reducers/entities/channels.test.js
  src/reducers/entities/channels.ts
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#1057 MM-22657 Partially Revert
  src/action_types/search.ts
  src/actions/search.ts
  src/reducers/requests/index.ts
  src/reducers/requests/search.ts
  src/types/requests.ts
Labels: 3: Reviews Complete

#1055 [MM-14661] - Add "mattermost://" to the list of hard-coded URL schemes
  src/constants/general.ts
Labels: 3: Reviews Complete
