Repository mattermost/mattermost-redux, pull requests merged in 2020-09, with the labels that each got.

#1226 [MM-27274] Add `convert_public_channel` permission
  src/constants/permissions.ts
Labels: 4: Reviews Complete

#1230 [MM-27864] Added page() method from rudder as pageVisited
  src/client/client4.ts
Labels: 4: Reviews Complete

#1231 [MM-28210] actions/users: add options to get profiles in channel
  src/actions/users.ts
  src/client/client4.ts
Labels: 4: Reviews Complete

#1224 MM-27352: add ldap certificate support
  src/action_types/admin.ts
  src/actions/admin.test.js
  src/actions/admin.ts
  src/client/client4.ts
Labels: 4: Reviews Complete

#1236 [MM-20548] Add missing type for `myUserAccessTokens` reducer
  src/reducers/entities/users.ts
  src/store/initial_state.ts
  src/types/users.ts
Labels: 4: Reviews Complete

#1222 MM-28005: Add config setting for LdapPictureAttributeSet
  src/types/config.ts
Labels: 4: Reviews Complete

#1234 MM-27750 Add API's for in product notices feature
  src/actions/teams.ts
  src/client/client4.ts
  src/types/product_notices.ts
  src/types/websocket.ts
Labels: 4: Reviews Complete, CherryPick/Approved

#1241 Automated cherry pick of #1234
  src/actions/teams.ts
  src/client/client4.ts
  src/types/product_notices.ts
  src/types/websocket.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1240 MM-28290 Add option to not increment channel member counts on new post
  src/actions/channels.test.js
  src/actions/channels.ts
  src/reducers/entities/channels.ts
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done

#1244 Automated cherry pick of #1240
  src/actions/channels.test.js
  src/actions/channels.ts
  src/reducers/entities/channels.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1243 [MM-28972] Add `always_on` constant and option for new sidebar to be forced on
  src/constants/general.ts
  src/selectors/entities/preferences.ts
Labels: 4: Reviews Complete

#1247 Add post_id for FileInfo type
  src/types/files.ts
Labels: 4: Reviews Complete, Tests/Not Needed
