Repository mattermost/mattermost-redux, pull requests merged in 2020-01, with the labels that each got.

#1003 MM-20696: Use SAML Identity Provider Metadata for SAML setup
  src/action_types/admin.ts
  src/actions/admin.test.js
  src/actions/admin.ts
  src/client/client4.ts
  src/reducers/entities/admin.ts
Labels: 3: Reviews Complete, QA Review Done

#1030 MM-20627: Create SECURITY.md
  SECURITY.md
Labels: 3: Reviews Complete

#1006 MM-18903 - Removal of unused status flags in Integrations requests state object
  src/action_types/integrations.ts
  src/actions/integrations.test.js
  src/actions/integrations.ts
  src/reducers/requests/index.ts
  src/reducers/requests/integrations.ts
  src/store/initial_state.ts
  src/types/requests.ts
  src/types/store.ts
Labels: 3: Reviews Complete, QA Review Done

#1029 MM-19976 & MM-19978 - Guest accounts, guest user should not see members that share no channels with them
  src/action_types/users.ts
  src/actions/websocket.test.js
  src/actions/websocket.ts
  src/reducers/entities/channels.ts
  src/reducers/entities/users.ts
  src/utils/user_utils.ts
Labels: 2: QA Review, 3: Reviews Complete

#1020 [MM-20881] Selector and tests for new channel sidebar pref
  src/constants/preferences.ts
  src/selectors/entities/preferences.test.js
  src/selectors/entities/preferences.ts
  src/types/config.ts
Labels: 3: Reviews Complete

#1009 MM-20653: Add role drop-down to to chat-facing team groups
  src/action_types/groups.ts
  src/actions/groups.test.js
  src/actions/groups.ts
  src/client/client4.ts
  src/reducers/entities/groups.ts
  src/types/groups.ts
Labels: 3: Reviews Complete, QA Review Done

#1032 Thread fetching revert
  src/actions/posts.test.js
  src/actions/posts.ts
  src/client/client4.ts
  src/reducers/entities/posts.ts
Labels: QA Review Done

#1025 MM-20977 - Inviting multiple users with valid/allowed and invalid emails causes the invites for the valid users not to be sent
  src/actions/teams.ts
  src/types/teams.ts
Labels: 2: Dev Review, Tests/Not Needed

#1007 MM-13545 Removal of unused status flags in Schemes requests state object
  src/action_types/schemes.ts
  src/actions/schemes.test.js
  src/actions/schemes.ts
  src/reducers/requests/index.ts
  src/reducers/requests/schemes.ts
  src/store/initial_state.ts
  src/types/requests.ts
  src/types/store.ts
Labels: 3: Reviews Complete, QA Review Done

#967 [MM-19533] unread message count selector
  src/selectors/entities/channels.test.js
  src/selectors/entities/channels.ts
Labels: 3: Reviews Complete, QA Review Done

#1031 MM-20627: Update wording in SECURITY.md
  SECURITY.md
Labels: 3: Reviews Complete

#1023 MM-19606 - Rework prepackaged plugins
  src/client/client4.ts
  src/constants/plugins.ts
  src/reducers/entities/admin.test.js
  src/reducers/entities/admin.ts
Labels: 3: Reviews Complete

#1033 [MM-21514] Removing groups on channel page and then leaving page and coming back not showing correct groups
  src/reducers/entities/channels.ts
Labels: 3: Reviews Complete, QA Review Done

#1004 [MM-20804] Add "Unarchive Channel" option to the channel info screen
  src/action_types/channels.ts
  src/actions/channels.test.js
  src/actions/channels.ts
  src/actions/websocket.test.js
  src/actions/websocket.ts
  src/client/client4.ts
  src/constants/posts.ts
  src/constants/websocket.ts
  src/reducers/entities/channels.test.js
  src/reducers/entities/channels.ts
  src/types/posts.ts
  src/utils/post_list.ts
  src/utils/post_utils.test.js
Labels: 3: Reviews Complete, QA Review Done

#1035 MM-21726 Add theme type and function to set theme defaults
  src/constants/preferences.ts
  src/types/preferences.ts
  src/utils/theme_utils.test.js
  src/utils/theme_utils.ts
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#1036 Automated cherry pick of #1035
  src/constants/preferences.ts
  src/types/preferences.ts
  src/utils/theme_utils.test.js
  src/utils/theme_utils.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1027 MM-18901 - Remove unused status flags in requests/preferences.ts #12521
  src/action_types/preferences.ts
  src/actions/preferences.test.js
  src/actions/preferences.ts
  src/reducers/requests/index.ts
  src/reducers/requests/preferences.ts
  src/store/initial_state.ts
  src/types/requests.ts
  src/types/store.ts
Labels: 3: Reviews Complete, QA Review Done

#1039 Update PR template for TypeScript and added makefile command
  Makefile
  PULL_REQUEST_TEMPLATE.md
Labels: 3: Reviews Complete

#1034 MM-20977 - Inviting multiple users with valid/allowed and invalid emails causes the invites for the valid users not to be sent
  src/actions/teams.ts
  src/client/client4.ts
Labels: 3: Reviews Complete, CherryPick/Approved

#1040 Automated cherry pick of #1034
  src/actions/teams.ts
  src/client/client4.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1038 [MM-20020] Added tracking of manual status set by user and stopped status being set to online when manually set
  src/actions/websocket.test.js
  src/actions/websocket.ts
  src/reducers/entities/users.ts
  src/selectors/entities/users.ts
  src/store/initial_state.ts
  src/types/users.ts
Labels: 3: Reviews Complete, CherryPick/Approved

#1042 Automated cherry pick of #1038
  src/actions/websocket.test.js
  src/actions/websocket.ts
  src/reducers/entities/users.ts
  src/selectors/entities/users.ts
  src/store/initial_state.ts
  src/types/users.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1037 MM-21977 Upgrade @types/jest to 24.9.0
  package-lock.json
  package.json
Labels: 3: Reviews Complete, CherryPick/Approved

#1043 Automated cherry pick of #1037
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1041 MM-21890: add team_display_name to Channel object
  src/types/channels.ts
Labels: CherryPick/Approved, QA Review Done

#1044 Automated cherry pick of #1041
  package-lock.json
  src/types/channels.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed
