Repository mattermost/mattermost-redux, pull requests merged in 2020-06, with the labels that each got.

#1166 MM-23573: Remove Segment.
  src/client/client4.ts
Labels: 4: Reviews Complete

#1137 Fixing small problems around counting replies
  src/actions/posts.ts
  src/reducers/entities/posts.test.js
  src/reducers/entities/posts.ts
  src/selectors/entities/posts.ts
Labels: 4: Reviews Complete

#1169 [MM-25771] Add filter for selecting profiles that are not deleted
  src/selectors/entities/users.test.js
  src/selectors/entities/users.ts
Labels: 4: Reviews Complete, CherryPick/Approved

#1170 Automated cherry pick of #1169
  src/selectors/entities/users.test.js
  src/selectors/entities/users.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1165 MM-24917 Update channel object last_post_at when new message is received
  src/reducers/entities/channels.test.js
  src/reducers/entities/channels.ts
  src/types/config.ts
Labels: 4: Reviews Complete

#1174 [MM-24708] Added new preference constant for What's New modal
  src/constants/preferences.ts
Labels: 4: Reviews Complete

#1172 [MM-25325] Add AdminState types to redux
  src/client/client4.ts
  src/reducers/entities/admin.ts
  src/reducers/entities/general.ts
  src/selectors/entities/channels.ts
  src/store/initial_state.ts
  src/types/admin.ts
  src/types/config.ts
  src/types/plugins.ts
Labels: 4: Reviews Complete

#1175 [MM-25325] Missed typing environmentConfig on AdminState
  src/reducers/entities/admin.ts
  src/types/admin.ts
Labels: 4: Reviews Complete

#1173 Add missing fields to UserProfile
  src/types/users.ts
Labels: 4: Reviews Complete

#1176 [MM-25325] Missed LDAP group typing in the reducer
  src/actions/admin.test.js
  src/reducers/entities/admin.ts
  src/types/admin.ts
  src/types/groups.ts
Labels: 2: Dev Review

#1153 MM-24682: don't mutate on RECEIVED_CHANNELS
  src/reducers/entities/channels.test.js
  src/reducers/entities/channels.ts
Labels: 4: Reviews Complete

#1177 MM-24914 Attach sidebar logic to server
  src/actions/channel_categories.test.js
  src/actions/channel_categories.ts
  src/actions/channels.test.js
  src/actions/channels.ts
  src/client/client4.ts
  src/constants/channel_categories.ts
  src/reducers/entities/channel_categories.test.js
  src/reducers/entities/channel_categories.ts
  src/selectors/entities/channel_categories.ts
  src/types/channel_categories.ts
  test/test_helper.js
Labels: 4: Reviews Complete

#1167 [MM-25263] Add selector to get profiles in group
  src/action_types/groups.ts
  src/action_types/users.ts
  src/actions/groups.test.js
  src/actions/groups.ts
  src/actions/users.test.js
  src/actions/users.ts
  src/client/client4.ts
  src/reducers/entities/groups.ts
  src/reducers/entities/users.ts
  src/selectors/entities/groups.ts
  src/selectors/entities/users.test.js
  src/selectors/entities/users.ts
  src/store/initial_state.ts
  src/types/groups.ts
  src/types/users.ts
Labels: 4: Reviews Complete

#1168 MM-25261: Adds the 'include_deleted' parameter to the get and search …
  src/actions/channels.test.js
  src/actions/channels.ts
  src/client/client4.ts
Labels: 4: Reviews Complete

#1171 MM-11713: Allows edit others posts to function without edit own posts.
  src/utils/post_utils.test.js
  src/utils/post_utils.ts
Labels: 4: Reviews Complete

#1178 MM-26066 Changes to use rudder npm package
  package-lock.json
  package.json
  src/client/client4.ts
  src/client/index.ts
  src/client/rudder.ts
Labels: 4: Reviews Complete

#1181 MM-26339 - Add context and CommandArgs to dynamic autocomplete calls
  package-lock.json
  src/client/client4.ts
Labels: 4: Reviews Complete
