Repository mattermost/mattermost-redux, pull requests merged in 2020-03, with the labels that each got.

#1063 MM-22752 Preserve other teams channel membership
  src/reducers/entities/channels.ts
Labels: 3: Reviews Complete, CherryPick/Approved

#1064 Automated cherry pick of #1063
  src/reducers/entities/channels.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1065 MM-21707: define MANAGE_(OTHERS_)?BOTS
  src/constants/permissions.ts
Labels: 3: Reviews Complete

#1060 [MM-22276] Add roles constants
  src/constants/index.ts
  src/constants/roles.ts
  src/types/roles.ts
Labels: QA Review Done

#1052 MM-21584 Add initial state for channel categories
  src/action_types/channel_categories.ts
  src/action_types/index.ts
  src/actions/channel_categories.ts
  src/constants/channel_categories.ts
  src/constants/preferences.ts
  src/reducers/entities/channel_categories.test.js
  src/reducers/entities/channel_categories.ts
  src/reducers/entities/index.ts
  src/selectors/entities/channel_categories.test.js
  src/selectors/entities/channel_categories.ts
  src/selectors/entities/preferences.ts
  src/store/initial_state.ts
  src/types/channel_categories.ts
  src/types/store.ts
  src/utils/channel_utils.ts
  src/utils/preference_utils.ts
Labels: 3: Reviews Complete

#1068 Add custom ESLint rule to prevent passing getState into dispatch
  .eslintrc.json
  package-lock.json
  package.json
  src/actions/admin.ts
  src/actions/alerts.ts
  src/actions/channels.ts
  src/actions/files.ts
  src/actions/general.ts
  src/actions/helpers.ts
  src/actions/integrations.ts
  src/actions/posts.ts
  src/actions/roles.ts
  src/actions/schemes.ts
  src/actions/teams.ts
  src/actions/users.ts
  src/actions/websocket.ts
Labels: 3: Reviews Complete

#1069 MM-22975|MM-22934 Fix mobile archive channel on action and WS reconnect
  src/actions/websocket.test.js
  src/actions/websocket.ts
Labels: 3: Reviews Complete, CherryPick/Approved

#1071 Add types to channel category selectors
  src/selectors/entities/channel_categories.ts
Labels: 2: Dev Review

#1073 Add diagnostics_disabled event to whitelist.
  src/client/client4.ts
Labels: QA Review Done

#1077 MM-23091 - whitelist new events to support onboarding analytics
  src/client/client4.ts
Labels: 3: Reviews Complete, QA Review Done

#1075 MM-22577 Re-add autoclosing DMs for new selectors
  src/selectors/entities/channel_categories.test.js
  src/selectors/entities/channel_categories.ts
  src/selectors/entities/preferences.test.js
  src/selectors/entities/preferences.ts
  src/utils/channel_utils.ts
  test/merge_objects.js
Labels: 3: Reviews Complete

#1076 [MM-23095] - Update action to take into consideration system posts
  src/actions/posts.ts
Labels: 3: Reviews Complete

#1082 MM-23239 Only show the user's channels in the sidebar
  src/selectors/entities/channel_categories.test.js
  src/selectors/entities/channel_categories.ts
Labels: 3: Reviews Complete

#1083 MM-23266 Add selector to get sorted channels for all categories
  src/selectors/entities/channel_categories.test.js
  src/selectors/entities/channel_categories.ts
  src/selectors/entities/channels.test.js
  src/selectors/entities/channels.ts
  src/utils/channel_utils.ts
Labels: 3: Reviews Complete

#1059 [MM-21408] Get correct display name for DM and modals
  src/selectors/entities/preferences.ts
  src/selectors/entities/users.test.js
  src/selectors/entities/users.ts
  src/utils/user_utils.test.js
  src/utils/user_utils.ts
Labels: 3: Reviews Complete, QA Review Done

#1070 [MM-23103] Update selectTeam function to accept teamId string and Team object
  src/actions/teams.ts
Labels: 3: Reviews Complete, QA Review Done

#1088 [MM-23161] Refactor loadRolesIfNeeded
  src/actions/roles.test.js
  src/actions/roles.ts
Labels: 3: Reviews Complete

#1089 Channel Sidebar Organization Stage 1
  src/action_types/channel_categories.ts
  src/action_types/index.ts
  src/actions/channel_categories.ts
  src/constants/channel_categories.ts
  src/constants/preferences.ts
  src/reducers/entities/channel_categories.test.js
  src/reducers/entities/channel_categories.ts
  src/reducers/entities/index.ts
  src/selectors/entities/channel_categories.test.js
  src/selectors/entities/channel_categories.ts
  src/selectors/entities/channels.test.js
  src/selectors/entities/channels.ts
  src/selectors/entities/preferences.test.js
  src/selectors/entities/preferences.ts
  src/store/initial_state.ts
  src/types/channel_categories.ts
  src/types/config.ts
  src/types/store.ts
  src/utils/channel_utils.ts
  src/utils/preference_utils.ts
  test/merge_objects.js
Labels: 3: Reviews Complete

#1084 [MM-22212] Add channel scheme updated socket event
  src/actions/websocket.ts
  src/constants/websocket.ts
Labels: 2: Dev Review, QA Review Done

#1072 Remove not visible users when the user is a guest and is removed from a channel or team
  src/actions/websocket.test.js
  src/actions/websocket.ts
  src/selectors/entities/channels.test.js
  src/selectors/entities/channels.ts
Labels: CherryPick/Approved, QA Review Done

#1062 MM-10272: Handle pinned post count when a post is pinned ot unpinned.
  src/action_types/channels.ts
  src/actions/posts.test.js
  src/actions/posts.ts
  src/reducers/entities/channels.ts
  src/types/channels.ts
Labels: 3: Reviews Complete, QA Review Done

#1093 MM-23513 Default autoclosing DMs to true with new sidebar
  src/selectors/entities/preferences.test.js
  src/selectors/entities/preferences.ts
Labels: 3: Reviews Complete, CherryPick/Approved

#1095 Automated cherry pick of #1093
  src/selectors/entities/preferences.test.js
  src/selectors/entities/preferences.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1092 [MM-23427] Filter channels by DM_CHANNEL or GM_CHANNEL when grabbing groups
  src/selectors/entities/channels.ts
Labels: 3: Reviews Complete, CherryPick/Approved

#1097 Automated cherry pick of #1092
  src/selectors/entities/channels.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1098 MM-23554 Sort muted channels to the bottom of the new sidebar
  src/selectors/entities/channel_categories.test.js
  src/selectors/entities/channel_categories.ts
Labels: 3: Reviews Complete, CherryPick/Approved

#1100 Automated cherry pick of #1098
  src/selectors/entities/channel_categories.test.js
  src/selectors/entities/channel_categories.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1101 [MM-23629] Update TypeScript version to 3.7, typescript-eslint to 2.7
  package-lock.json
  package.json
Labels: 3: Reviews Complete

#1102 [MM-20550] Fixed broken type on getEmailInterval()
  src/utils/notify_props.ts
Labels: 3: Reviews Complete

#1103 [MM-23135] Don't re-sort channel sidebar if notification properties haven't changed
  src/actions/channels.ts
  src/utils/channel_utils.test.js
  src/utils/channel_utils.ts
Labels: 3: Reviews Complete

#1104 Adding missing types from search global state
  src/store/initial_state.ts
  src/types/search.ts
Labels: 3: Reviews Complete, QA Review Done, Tests/Not Needed

#1099 Update NOTICE.txt
  NOTICE.txt
Labels: CherryPick/Approved

#1107 Automated cherry pick of #1099
  NOTICE.txt
Labels: 3: Reviews Complete, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1091 [MM-21517] Add new options parameter to getTeamMembers to fix users not having their roles updated
  src/actions/teams.ts
  src/client/client4.ts
  src/constants/teams.ts
  src/types/teams.ts
Labels: 3: Reviews Complete, QA Review Done

#1108 [No-Ticket] Fix import path causing Server CI build failures
  src/types/search.ts
Labels: 3: Reviews Complete

#1110 MM-23542 new permission for system console access
  src/constants/permissions.ts
Labels: 3: Reviews Complete
