Repository mattermost/mattermost-redux, pull requests merged in 2020-10, with the labels that each got.

#1249 [MM-28217] Added CloudState entity and state to hold cloud customer
  src/action_types/cloud.ts
  src/action_types/index.ts
  src/actions/cloud.ts
  src/actions/index.ts
  src/client/client4.ts
  src/reducers/entities/cloud.ts
  src/reducers/entities/index.ts
  src/store/initial_state.ts
  src/types/cloud.ts
  src/types/store.ts
Labels: 4: Reviews Complete

#1248 [MM-28944] Mark the search as ended only when no more results returned
  src/actions/search.test.js
  src/actions/search.ts
Labels: 4: Reviews Complete

#1253 [MM-28714] Add is_paid_tier to Subscription type
  src/types/cloud.ts
Labels: 2: Dev Review

#1252 Define OpenGraphMetadata
  src/selectors/entities/posts.ts
  src/types/posts.ts
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#1254 Automated cherry pick of #1253
  src/types/cloud.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1255 MM-27454 - Added CWSUrl to client config
  src/types/config.ts
Labels: 4: Reviews Complete

#1256 Automated cherry pick of #1255
  src/types/config.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1242 [MM-27556] Add sys console ancillary permissions and ability to exclude roles
  src/constants/permissions.ts
  src/selectors/entities/users.ts
  src/utils/user_utils.test.js
  src/utils/user_utils.ts
Labels: 2: Dev Review, 3: QA Review, Lifecycle/1:stale

#1263 Rename userAccessTokensForUser to userAccessTokensByUser and fix the type
  src/reducers/entities/admin.ts
  src/types/admin.ts
Labels: 4: Reviews Complete

#1259 [MM-28218] Redux hooks for updating company info and address
  src/actions/cloud.ts
  src/client/client4.ts
  src/types/cloud.ts
Labels: 4: Reviews Complete

#1264 Added user_actual_id to rudder page event
  src/client/client4.ts
Labels: 4: Reviews Complete

#1265 Automated cherry pick of #1264
  src/client/client4.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1267 Automated cherry pick of #1259
  src/actions/cloud.ts
  src/client/client4.ts
  src/types/cloud.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1266 [MM-28214][MM-28216] Redux hooks for getting invoices
  src/action_types/cloud.ts
  src/actions/cloud.ts
  src/client/client4.ts
  src/reducers/entities/cloud.ts
  src/types/cloud.ts
Labels: 4: Reviews Complete

#1268 Automated cherry pick of #1266
  src/action_types/cloud.ts
  src/actions/cloud.ts
  src/client/client4.ts
  src/reducers/entities/cloud.ts
  src/types/cloud.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1260 MM-29679 Add memoization to getCustomEmojis
  src/selectors/entities/emojis.test.js
  src/selectors/entities/emojis.ts
Labels: 4: Reviews Complete

#1261 Addition of filenames field in Posts types
  src/types/posts.ts
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#1273 Automated cherry pick of #1271
  src/types/cloud.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1246 MM-27909: Add shared channel permission
  src/constants/permissions.ts
Labels: 4: Reviews Complete

#1270 MM-22845 Fix quick switcher results
  src/selectors/entities/users.test.js
  src/selectors/entities/users.ts
  src/utils/channel_utils.ts
  src/utils/user_utils.test.js
  src/utils/user_utils.ts
Labels: 2: Dev Review, CherryPick/Approved

#1274 Automated cherry pick of #1270
  src/selectors/entities/users.test.js
  src/selectors/entities/users.ts
  src/utils/channel_utils.ts
  src/utils/user_utils.test.js
  src/utils/user_utils.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1275 MM-28843 Add feature flags to the admin config struct.
  src/types/config.ts
Labels: 4: Reviews Complete

#1277 MM-29998 Add telemetry for in product notices
  src/client/client4.ts
Labels: 4: Reviews Complete, CherryPick/Approved

#1278 Automated cherry pick of #1277
  src/client/client4.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1257 MM-28833 Remove computed details from getChannel selector
  src/selectors/entities/channels.test.js
  src/selectors/entities/channels.ts
Labels: 4: Reviews Complete
