Repository mattermost/mattermost-redux, pull requests merged in 2021-03, with the labels that each got.

#1379 Add User Agent to call context
  src/client/client4.ts
  src/types/apps.ts
Labels: 4: Reviews Complete

#1380 Add warning into code about using apps related code
  src/action_types/apps.ts
  src/actions/apps.ts
  src/client/client4.ts
  src/constants/apps.ts
  src/reducers/entities/apps.ts
  src/selectors/entities/apps.ts
  src/types/apps.ts
  src/types/marketplace.ts
  src/utils/marketplace.ts
Labels: 4: Reviews Complete

#1378 Add support for search files
  src/action_types/files.ts
  src/action_types/search.ts
  src/actions/files.test.js
  src/actions/files.ts
  src/actions/search.test.js
  src/actions/search.ts
  src/client/client4.ts
  src/reducers/entities/files.test.js
  src/reducers/entities/files.ts
  src/reducers/entities/search.test.js
  src/reducers/entities/search.ts
  src/selectors/entities/files.ts
  src/store/initial_state.ts
  src/types/files.ts
  src/types/search.ts
Labels: 4: Reviews Complete

#1388 Change user agent property in get bindings query
  src/client/client4.ts
Labels: 4: Reviews Complete

#1385 Update NOTICE.txt
  NOTICE.txt
Labels: 4: Reviews Complete, CherryPick/Approved

#1390 Automated cherry pick of #1385
  NOTICE.txt
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1394 [MM-33511] Apps might not have a RootURL
  src/types/apps.ts
Labels: 4: Reviews Complete

#1391 Change call type submit and call response ok to not be empty strings
  src/constants/apps.ts
Labels: 4: Reviews Complete

#1393 MM-24009: remove redux-action-buffer
  NOTICE.txt
  package-lock.json
  package.json
  src/store/configureStore.dev.ts
  src/store/configureStore.prod.ts
  src/store/middleware.ts
  src/types/module.d.ts
Labels: 4: Reviews Complete

#1382 [GH-16739] Add optional props attribute to channel type
  src/types/channels.ts
Labels: 2: Dev Review

#1392 [MM-35501] Remove Determining Ancillary Permissions from Frontend to Backend
  src/constants/permissions.ts
Labels: 4: Reviews Complete

#1399 Disable check-deps ci step
  .circleci/config.yml
Labels: 4: Reviews Complete

#1377 MM-32351 Add Compliance Subsections
  src/constants/permissions.ts
  src/constants/permissions_sysconsole.ts
Labels: 2: Dev Review

#1383 MM-32785 CenterChannel: Collapse Replies (show only root posts)
  src/actions/posts.ts
  src/constants/preferences.ts
  src/selectors/entities/preferences.ts
  src/selectors/entities/threads.ts
Labels: 2: Dev Review

#1395 MM-32642 - increase invite other visibility
  src/selectors/entities/admin.ts
Labels: 2: Dev Review

#1381 Add binding validation on fetch bindings
  src/reducers/entities/__snapshots__/apps.test.ts.snap
  src/reducers/entities/apps.test.ts
  src/reducers/entities/apps.ts
  src/utils/apps.ts
Labels: 2: Dev Review

#1404 MM-32350 Integrations
  src/constants/permissions.ts
  src/constants/permissions_sysconsole.ts
Labels: 4: Reviews Complete

#1408 Remove async/await and some mocks from tests
  src/actions/admin.test.js
  src/actions/bots.test.js
  src/actions/channel_categories.test.js
  src/actions/channels.test.js
  src/actions/emojis.test.js
  src/actions/errors.test.js
  src/actions/files.test.js
  src/actions/general.test.js
  src/actions/groups.test.js
  src/actions/helpers.test.js
  src/actions/integrations.test.js
  src/actions/jobs.test.js
  src/actions/posts.test.js
  src/actions/preferences.test.js
  src/actions/roles.test.js
  src/actions/schemes.test.js
  src/actions/search.test.js
  src/actions/teams.test.js
  src/actions/threads.test.js
  src/actions/users.test.js
  src/selectors/entities/preferences.test.js
  src/store/reducer_registry.test.js
  src/utils/theme_utils.test.js
  test/test_helper.js
  test/test_store.js
Labels: 4: Reviews Complete

#1406 Use call type on the path
  src/client/client4.ts
  src/types/apps.ts
  src/types/integrations.ts
Labels: 4: Reviews Complete

#1389 [MM-32343] Environment SubSection
  src/constants/permissions.ts
  src/constants/permissions_sysconsole.ts
Labels: 4: Reviews Complete

#1403 MM-32347 Site Subsections
  src/constants/permissions.ts
  src/constants/permissions_sysconsole.ts
Labels: 3: QA Review

#1412 [GH_16717/MM_20389] Migrate 'components/signup/signup_controller' module and associated tests to TypeScript
  src/types/config.ts
Labels: 4: Reviews Complete

#1369 Added EnableCustomStatuses in AdminConfig for cypress testing in webapp
  src/types/config.ts
Labels: 4: Reviews Complete

#1401 Adding subsection permissions for Authentication
  src/constants/permissions.ts
  src/constants/permissions_sysconsole.ts
Labels: 4: Reviews Complete

#1414 Cloud Apps mattermost-redux changes
  src/action_types/apps.ts
  src/action_types/index.ts
  src/actions/apps.ts
  src/client/client4.ts
  src/constants/apps.ts
  src/reducers/entities/__snapshots__/apps.test.ts.snap
  src/reducers/entities/apps.test.ts
  src/reducers/entities/apps.ts
  src/reducers/entities/index.ts
  src/selectors/entities/apps.ts
  src/store/initial_state.ts
  src/types/apps.ts
  src/types/integrations.ts
  src/types/marketplace.ts
  src/types/plugins.ts
  src/types/store.ts
  src/utils/apps.ts
  src/utils/marketplace.ts
Labels: 4: Reviews Complete

#1407 MM-30407: improve slow typing
  src/selectors/entities/channels.ts
  src/utils/channel_utils.ts
Labels: 4: Reviews Complete

#1413 [MM-28837] Data retention new endpoints
  src/action_types/admin.ts
  src/actions/admin.ts
  src/client/client4.ts
  src/reducers/entities/admin.ts
  src/reducers/entities/channels.test.js
  src/reducers/entities/channels.ts
  src/reducers/entities/teams.ts
  src/selectors/entities/admin.ts
  src/selectors/entities/channels.ts
  src/selectors/entities/teams.ts
  src/store/initial_state.ts
  src/types/admin.ts
  src/types/channels.ts
  src/types/data_retention.ts
  src/types/teams.ts
Labels: 4: Reviews Complete

#1419 Update README.md
  README.md
Labels: 4: Reviews Complete

#1421 Automated cherry pick of #1407
  src/selectors/entities/channels.ts
  src/utils/channel_utils.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1422 Automated cherry pick of #1407
  .circleci/config.yml
  src/selectors/entities/channels.ts
  src/utils/channel_utils.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1423 Automated cherry pick of #1407
  src/selectors/entities/channels.ts
  src/utils/channel_utils.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed
