Repository mattermost/mattermost-redux, pull requests merged in 2021-01, with the labels that each got.

#1325 [MM-28000] Fix system manager can download export files without right permissions
  src/constants/permissions.ts
Labels: 4: Reviews Complete

#1326 MM-30443 Add shouldShowUnreadsCategory selector for new sidebar
  src/constants/preferences.ts
  src/selectors/entities/preferences.test.js
  src/selectors/entities/preferences.ts
Labels: 4: Reviews Complete

#1327 Add types for command autocomplete and interactive dialog
  src/types/integrations.ts
Labels: 2: Dev Review

#1322 update types for dynamic modals
  src/constants/apps.ts
  src/selectors/entities/apps.ts
  src/types/apps.ts
Labels: 4: Reviews Complete

#1310 [MM-27927] - Add user preference for limit on dms and gms
  src/constants/preferences.ts
  src/selectors/entities/channel_categories.test.js
  src/selectors/entities/channel_categories.ts
Labels: 4: Reviews Complete

#1332 Add exported type to getTheme
  src/selectors/entities/preferences.ts
Labels: 4: Reviews Complete

#1333 Temporarily fix typing issues
  src/types/config.ts
  src/types/posts.ts
Labels: 4: Reviews Complete

#1334 type fix
  src/types/threads.ts
Labels: 4: Reviews Complete

#1316 [MM-30851] Replace ExperimentalChannelSidebarOrganization with EnableLegacySidebar
  src/actions/channel_categories.test.js
  src/actions/channels.test.js
  src/actions/channels.ts
  src/selectors/entities/channels.test.js
  src/selectors/entities/channels.ts
  src/selectors/entities/preferences.test.js
  src/selectors/entities/preferences.ts
  src/types/config.ts
Labels: 4: Reviews Complete

#1335 MM-32099 Don't change category sorting method to manual when dragging and dropping
  src/actions/channel_categories.test.js
  src/actions/channel_categories.ts
Labels: 4: Reviews Complete

#1330 MM-31882 - Add CodeQL check
  .github/workflows/codeql-analysis.yml
Labels: 2: Dev Review

#1339 MM-32197 Use other timestamps when autohiding DMs/GMs
  src/selectors/entities/channel_categories.test.js
  src/selectors/entities/channel_categories.ts
Labels: 4: Reviews Complete, CherryPick/Approved

#1340 Automated cherry pick of #1339
  src/selectors/entities/channel_categories.test.js
  src/selectors/entities/channel_categories.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1331 [MM-31791] Support Packet Generation REDUX
  src/types/config.ts
Labels: 4: Reviews Complete
