Repository mattermost/mattermost-redux, pull requests merged in 2021-02, with the labels that each got.

#1343 [MM-31497] - Prevent end users from inviting people and exceeding the free tier limits
  src/action_types/cloud.ts
  src/actions/cloud.ts
  src/client/client4.ts
  src/reducers/entities/cloud.ts
  src/types/cloud.ts
Labels: 2: Dev Review, 3: QA Review

#1345 MM-32310 Update redux with collapsed thread related changes
  jest.config.js
  src/actions/threads.test.js
  src/actions/threads.ts
  src/client/client4.ts
  src/reducers/entities/threads.test.js
  src/reducers/entities/threads.ts
  src/selectors/entities/general.test.js
  src/selectors/entities/general.ts
  src/selectors/entities/threads.ts
  src/types/config.ts
  src/types/threads.ts
Labels: 2: Dev Review

#1354 Correctly type signature of executeCommand
  src/actions/integrations.ts
  src/client/client4.ts
  src/types/integrations.ts
Labels: 4: Reviews Complete

#1351 MM-31503 - create new restrict screens 4 users
  src/selectors/entities/general.ts
Labels: 2: Dev Review

#1352 [MM-32476] Apps in the Marketplace
  src/client/client4.ts
  src/types/apps.ts
  src/types/marketplace.ts
  src/types/plugins.ts
  src/utils/marketplace.ts
Labels: 2: Dev Review

#1353 MM-32525 added unread_mentions_per_channel
  src/action_types/threads.ts
  src/actions/threads.ts
  src/client/client4.ts
  src/reducers/entities/threads.test.js
  src/reducers/entities/threads.ts
  src/types/threads.ts
Labels: 4: Reviews Complete

#1358 [MM-31497] - Default SubscriptionStats to null
  src/reducers/entities/cloud.ts
Labels: 2: Dev Review

#1305 Add shared channels to license
  src/types/config.ts
Labels: 2: Dev Review

#1355 MM-28736 Update dependencies
  .circleci/config.yml
  .eslintrc.json
  jest.config.js
  package-lock.json
  package.json
  rollup.config.js
  src/actions/general.ts
  src/actions/posts.test.js
  src/actions/posts.ts
  src/actions/preferences.ts
  src/client/client4.ts
  src/client/websocket_client.ts
  src/reducers/entities/channels.ts
  src/reducers/entities/gifs.ts
  src/reducers/entities/posts.ts
  src/reducers/websocket.ts
  src/selectors/entities/groups.ts
  src/selectors/entities/posts.ts
  src/store/helpers.ts
  src/store/reducer_registry.ts
  src/types/actions.ts
  src/types/client4.ts
  src/types/users.ts
  src/utils/delayed_action.ts
  src/utils/event_emitter.ts
  src/utils/gfycat_sdk.ts
  src/utils/helpers.ts
  src/utils/i18n_utils.ts
  src/utils/key_mirror.ts
Labels: 4: Reviews Complete

#1357 [MM-31502] - Add Notify Admin link to invitation modal
  src/client/client4.ts
Labels: 2: Dev Review

#1342 [MM-32087] - Add theme variable for sidebar team bar
  src/constants/preferences.ts
  src/selectors/entities/preferences.test.js
  src/selectors/entities/preferences.ts
  src/types/preferences.ts
  src/utils/theme_utils.test.js
  src/utils/theme_utils.ts
Labels: 4: Reviews Complete

#1349 Custom status feature
  src/actions/preferences.ts
  src/actions/users.ts
  src/client/client4.ts
  src/constants/preferences.ts
  src/types/config.ts
  src/types/users.ts
Labels: 4: Reviews Complete

#1365 Automated cherry pick of #1349
  src/actions/preferences.ts
  src/actions/users.ts
  src/client/client4.ts
  src/constants/preferences.ts
  src/types/config.ts
  src/types/users.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1356 [MM-32352] Add Experiment Sub Section
  src/constants/permissions.ts
  src/constants/permissions_sysconsole.ts
Labels: 4: Reviews Complete, Do Not Merge/Awaiting PR

#1372 MM-33209 Downgrade serialize-error
  package-lock.json
  package.json
Labels: 4: Reviews Complete, CherryPick/Approved

#1373 Automated cherry pick of #1372
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1366 [MM-32691] - Send email when the users are not able to join a workspace
  src/client/client4.ts
Labels: 4: Reviews Complete

#1371 Fix linter errors on feature/cloud-apps
  src/types/apps.ts
  src/utils/marketplace.ts
Labels: 2: Dev Review

#1370 [MM-31508] Rename URL to Path in Call
  src/types/apps.ts
Labels: 4: Reviews Complete
